# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Credential proxy — HTTP-over-Unix-socket reverse proxy with secret injection.

This module has **zero terok imports**.  It is a self-contained security
component: a standalone daemon that listens on a Unix socket, validates
phantom tokens against a sqlite3 database, injects real credentials from
the same database, and forwards requests to upstream API servers.

Task containers see only phantom API keys (worthless outside the proxy).
Real secrets never enter the container filesystem or environment.

Startup::

    terok-credential-proxy \\
        --socket-path /run/terok/credential-proxy.sock \\
        --db-path ~/.local/share/terok/proxy/credentials.db \\
        --routes-file ~/.local/share/terok/proxy/routes.json

Route config (JSON, generated by terok-executor from YAML registry)::

    {
      "claude": {
        "upstream": "https://api.anthropic.com",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer "
      }
    }
"""

from __future__ import annotations

import argparse
import asyncio
import json
import logging
import signal
import socket
import sqlite3
import time
from pathlib import Path

from aiohttp import ClientSession, ClientTimeout, ServerDisconnectedError, TCPConnector, web

_logger = logging.getLogger("terok-credential-proxy")

# Typed app keys (avoids NotAppKeyWarning on aiohttp >= 3.9)
_KEY_ROUTES = web.AppKey("routes", "_RouteTable")
_KEY_TOKEN_DB = web.AppKey("token_db", "_TokenDB")
_KEY_CLIENT = web.AppKey("client_session", ClientSession)
_KEY_REFRESH_TASK = web.AppKey("refresh_task", object)  # asyncio.Task

_REFRESH_INTERVAL = 300  # seconds between background refresh checks
_IDEMPOTENT_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})
_REFRESH_BUFFER = 600  # refresh this many seconds before expiry

# ---------------------------------------------------------------------------
# Route + credential loading (inlined, no terok imports)
# ---------------------------------------------------------------------------


class _RouteTable:
    """Provider routing table loaded from a JSON file."""

    def __init__(self, routes_path: str) -> None:
        with open(routes_path) as f:
            self._routes: dict[str, dict] = json.load(f)
        for name, cfg in self._routes.items():
            if "upstream" not in cfg:
                raise ValueError(f"Route '{name}' missing required 'upstream' field")

    def get(self, provider: str) -> dict | None:
        """Return the route config for *provider*, or ``None``."""
        return self._routes.get(provider)


class _TokenDB:
    """Read-only sqlite3 accessor for phantom token lookups and credential loading."""

    def __init__(self, db_path: str) -> None:
        # check_same_thread=False is safe: this is a read-only accessor and
        # aiohttp runs handlers in a single event loop thread.
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.execute("PRAGMA journal_mode=WAL")

    def lookup_token(self, token: str) -> dict | None:
        """Return ``{scope, task, credential_set, provider}`` or ``None``."""
        row = self._conn.execute(
            "SELECT scope, task, credential_set, provider FROM proxy_tokens WHERE token = ?",
            (token,),
        ).fetchone()
        if row is None:
            return None
        return {"scope": row[0], "task": row[1], "credential_set": row[2], "provider": row[3]}

    def load_credential(self, credential_set: str, provider: str) -> dict | None:
        """Return parsed credential data dict, or ``None``."""
        row = self._conn.execute(
            "SELECT data FROM credentials WHERE credential_set = ? AND provider = ?",
            (credential_set, provider),
        ).fetchone()
        return json.loads(row[0]) if row else None

    def list_refreshable(self) -> list[tuple[str, str, dict]]:
        """Return ``(credential_set, provider, data)`` for OAuth creds with a refresh token."""
        rows = self._conn.execute(
            "SELECT credential_set, provider, data FROM credentials"
        ).fetchall()
        result: list[tuple[str, str, dict]] = []
        for cs, prov, raw in rows:
            data = json.loads(raw)
            if data.get("type") == "oauth" and data.get("refresh_token"):
                result.append((cs, prov, data))
        return result

    def update_credential(self, credential_set: str, provider: str, data: dict) -> None:
        """Update the data blob for an existing credential."""
        self._conn.execute(
            "UPDATE credentials SET data = ? WHERE credential_set = ? AND provider = ?",
            (json.dumps(data), credential_set, provider),
        )
        self._conn.commit()

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()

    def __del__(self) -> None:
        """Best-effort close on garbage collection."""
        try:
            self._conn.close()
        except Exception:  # noqa: BLE001
            pass


# ---------------------------------------------------------------------------
# Auth extraction helpers
# ---------------------------------------------------------------------------

_AUTH_HEADERS = ("authorization", "x-api-key", "private-token")


def _extract_phantom_token(request: web.Request) -> str | None:
    """Extract a phantom token from Authorization or X-Api-Key headers."""
    for header in _AUTH_HEADERS:
        value = request.headers.get(header)
        if not value:
            continue
        # Strip "Bearer ", "token ", etc. prefixes
        if " " in value:
            return value.split(None, 1)[1]
        return value
    return None


# ---------------------------------------------------------------------------
# Request handler
# ---------------------------------------------------------------------------


async def _handle_request(request: web.Request) -> web.StreamResponse:
    """Authenticate, route by token, inject credentials, and forward to upstream."""
    routes: _RouteTable = request.app[_KEY_ROUTES]
    token_db: _TokenDB = request.app[_KEY_TOKEN_DB]

    # 1. Validate phantom token
    phantom = _extract_phantom_token(request)
    if not phantom:
        _logger.warning("%s %s -> 401 Missing authentication", request.method, request.path)
        return web.Response(status=401, text="Missing authentication")

    token_info = token_db.lookup_token(phantom)
    if token_info is None:
        # Workaround: Claude Code shows "Claude API" instead of the subscription
        # plan when CLAUDE_CODE_OAUTH_TOKEN env var is the token source.  For
        # Claude OAuth setups the static marker in .credentials.json is used as
        # the access token instead of a per-task phantom.  Accept it here and
        # route to the Claude credential in the default set.
        from .constants import PHANTOM_CREDENTIALS_MARKER

        if phantom == PHANTOM_CREDENTIALS_MARKER:
            # Hardcoded to credential_set="default" — Claude OAuth is a
            # shared credential, per-scope credential sets are not
            # supported for this path.
            _logger.debug("Accepting static phantom marker for Claude OAuth")
            token_info = {
                "scope": "__static__",
                "task": "__static__",
                "credential_set": "default",
                "provider": "claude",
            }
        else:
            _logger.warning("%s %s -> 401 Invalid token", request.method, request.path)
            return web.Response(status=401, text="Invalid token")

    # 2. Route by token's provider
    provider = token_info["provider"]
    route = routes.get(provider)
    if route is None:
        _logger.warning(
            "%s %s -> 404 No route for provider: %s", request.method, request.path, provider
        )
        return web.Response(status=404, text=f"No route for provider: {provider}")
    rest = request.path

    # 3. Load real credential
    cred = token_db.load_credential(token_info["credential_set"], provider)
    if cred is None:
        _logger.warning(
            "No credential for provider %r in set %r", provider, token_info["credential_set"]
        )
        return web.Response(status=502, text="Credential not configured for this provider")

    # Determine the real auth value and header based on credential type.
    # OAuth tokens use "Authorization: Bearer <token>"; API keys use the
    # route-configured header (e.g. "x-api-key: <key>").
    # Legacy rows without "type" are detected by the presence of "access_token".
    cred_type = cred.get("type", "")
    is_oauth = cred_type == "oauth" or (not cred_type and "access_token" in cred)
    if is_oauth:
        real_token = cred.get("access_token")
        if not real_token:
            _logger.error("Credential for %r is OAuth but missing access_token", provider)
            return web.Response(status=502, text="Credential misconfigured")
        auth_header = "Authorization"
        auth_prefix = "Bearer "
        oauth_beta_header = cred.get("beta_header", "oauth-2025-04-20")
    else:
        real_token = cred.get("token") or cred.get("key")
        if not real_token:
            _logger.error("Credential for %r has no usable token field", provider)
            return web.Response(status=502, text="Credential misconfigured")
        auth_header = route.get("auth_header", "Authorization")
        auth_prefix = route.get("auth_prefix", "Bearer ")
        # "dynamic" means auto-detect — for API keys, use x-api-key
        if auth_header == "dynamic":
            auth_header = "x-api-key"
            auth_prefix = ""

    # 4. Build upstream request — strip phantom auth, inject real auth
    from urllib.parse import urlparse

    parsed = urlparse(route["upstream"])
    upstream_url = f"{parsed.scheme}://{parsed.netloc}{rest}"
    if request.query_string:
        upstream_url += f"?{request.query_string}"

    headers = {
        k: v
        for k, v in request.headers.items()
        if k.lower() not in _AUTH_HEADERS and k.lower() != "host"
    }
    headers[auth_header] = f"{auth_prefix}{real_token}"
    if is_oauth and oauth_beta_header:
        existing = headers.get("anthropic-beta", "")
        if oauth_beta_header not in existing:
            headers["anthropic-beta"] = f"{existing},{oauth_beta_header}".lstrip(",")

    # 5. Forward and stream response
    session: ClientSession = request.app[_KEY_CLIENT]
    # Read the body once (streaming body can only be consumed once).
    body = await request.read() if request.can_read_body else None
    # Only retry idempotent methods (or those with an Idempotency-Key header) to
    # avoid replaying non-idempotent writes on stale-connection recovery.
    can_retry = (
        request.method.upper() in _IDEMPOTENT_METHODS or "idempotency-key" in request.headers
    )
    for attempt in range(2 if can_retry else 1):
        # Track whether __aenter__ succeeded so we never retry after resp.prepare().
        connection_established = False
        try:
            async with session.request(
                request.method,
                upstream_url,
                headers=headers,
                data=body,
                allow_redirects=False,
                timeout=ClientTimeout(connect=10, sock_read=60),
            ) as upstream:
                connection_established = True
                # Build response with upstream status + headers
                resp = web.StreamResponse(status=upstream.status)
                # Forward selected headers
                for hdr in ("content-type", "transfer-encoding", "cache-control"):
                    val = upstream.headers.get(hdr)
                    if val:
                        resp.headers[hdr] = val
                await resp.prepare(request)

                async for chunk in upstream.content.iter_any():
                    await resp.write(chunk)
                await resp.write_eof()
                return resp
        except ServerDisconnectedError:
            if not connection_established and attempt == 0 and can_retry:
                _logger.debug("Upstream %s disconnected on pooled conn, retrying", provider)
                continue
            _logger.error("Upstream %s disconnected on fresh connection", provider)
            return web.Response(status=502, text="Upstream disconnected")
        except Exception as exc:
            _logger.error("Upstream request to %s failed: %s", provider, exc)
            return web.Response(status=502, text="Upstream request failed")
    return web.Response(status=502, text="Upstream disconnected")  # unreachable


# ---------------------------------------------------------------------------
# Background OAuth token refresh
# ---------------------------------------------------------------------------


async def _do_oauth_refresh(
    session: ClientSession, provider: str, oauth_cfg: dict, cred: dict
) -> dict:
    """Call the provider's token endpoint and return an updated credential dict.

    Raises on network or HTTP errors so callers can log and continue.
    """
    payload = {
        "grant_type": "refresh_token",
        "refresh_token": cred["refresh_token"],
        "client_id": oauth_cfg["client_id"],
    }
    if "scope" in oauth_cfg:
        payload["scope"] = oauth_cfg["scope"]
    if "client_secret" in oauth_cfg:
        payload["client_secret"] = oauth_cfg["client_secret"]

    # NOTE: RFC 6749 specifies application/x-www-form-urlencoded for token
    # requests, but Anthropic's endpoint expects JSON (confirmed from Claude
    # Code v2.1.86 source).  Future providers (e.g. Codex/OpenAI) may need
    # form-encoded — add a per-provider `token_content_type` YAML field then.
    async with session.post(
        oauth_cfg["token_url"],
        json=payload,
        timeout=ClientTimeout(total=15),
    ) as resp:
        if resp.status != 200:
            body = await resp.text()
            raise RuntimeError(f"Token refresh failed ({resp.status}): {body}")
        data = await resp.json()

    return {
        **cred,
        "access_token": data["access_token"],
        "refresh_token": data.get("refresh_token", cred["refresh_token"]),
        "expires_at": time.time() + data.get("expires_in", 28800),
    }


async def _refresh_all(app: web.Application) -> None:
    """Check all OAuth credentials and refresh any that are expired or expiring soon."""
    token_db: _TokenDB = app[_KEY_TOKEN_DB]
    routes: _RouteTable = app[_KEY_ROUTES]
    session: ClientSession = app[_KEY_CLIENT]

    for cs, provider, cred in token_db.list_refreshable():
        route = routes.get(provider)
        if not route or "oauth_refresh" not in route:
            continue
        expires_at = cred.get("expires_at")
        if expires_at and time.time() < expires_at - _REFRESH_BUFFER:
            continue  # still valid

        _logger.info("Refreshing OAuth token for %s (credential_set=%s)", provider, cs)
        try:
            new_cred = await _do_oauth_refresh(session, provider, route["oauth_refresh"], cred)
            token_db.update_credential(cs, provider, new_cred)
            _logger.info(
                "Refreshed OAuth token for %s (expires in %ds)",
                provider,
                int(new_cred["expires_at"] - time.time()),
            )
        except Exception:
            _logger.exception("Failed to refresh OAuth token for %s", provider)


async def _refresh_loop(app: web.Application) -> None:
    """Run an immediate refresh check, then repeat every ``_REFRESH_INTERVAL`` seconds."""
    while True:
        try:
            await _refresh_all(app)
        except asyncio.CancelledError:
            raise
        except Exception:
            _logger.exception("OAuth refresh cycle failed")
        await asyncio.sleep(_REFRESH_INTERVAL)


# ---------------------------------------------------------------------------
# Application lifecycle
# ---------------------------------------------------------------------------


async def _on_startup(app: web.Application) -> None:
    """Create the shared HTTP client session and start background refresh."""
    # keepalive_timeout=30 ensures we retire connections before upstream servers
    # close them (~60-90s typical for Anthropic/OpenAI), preventing stale-pool 502s.
    connector = TCPConnector(enable_cleanup_closed=True, keepalive_timeout=30)
    app[_KEY_CLIENT] = ClientSession(connector=connector)
    app[_KEY_REFRESH_TASK] = asyncio.create_task(_refresh_loop(app))


async def _on_cleanup(app: web.Application) -> None:
    """Close client session, cancel background tasks, and close token DB."""
    task = app.get(_KEY_REFRESH_TASK)
    if task is not None:
        task.cancel()
        try:
            await task
        except asyncio.CancelledError:
            pass
    await app[_KEY_CLIENT].close()
    app[_KEY_TOKEN_DB].close()


async def _handle_health(_request: web.Request) -> web.Response:
    """Return 200 — unauthenticated readiness probe for lifecycle management."""
    return web.json_response({"status": "ok"})


def _build_app(db_path: str, routes_path: str) -> web.Application:
    """Construct the aiohttp application."""
    app = web.Application()
    app[_KEY_ROUTES] = _RouteTable(routes_path)
    app[_KEY_TOKEN_DB] = _TokenDB(db_path)
    app.on_startup.append(_on_startup)
    app.on_cleanup.append(_on_cleanup)
    from .constants import HEALTH_PATH

    app.router.add_get(HEALTH_PATH, _handle_health)
    app.router.add_route("*", "/{tail:.*}", _handle_request)
    return app


def _systemd_sockets() -> tuple[socket.socket | None, socket.socket | None]:
    """Return ``(unix_sock, tcp_sock)`` inherited from systemd, or ``(None, None)``.

    Implements the ``sd_listen_fds(3)`` protocol.  The socket unit
    declares two ``ListenStream=`` entries (Unix path first, TCP port
    second), so systemd passes file descriptors 3 and 4 respectively
    when ``LISTEN_FDS=2``.
    """
    import os

    if os.environ.get("LISTEN_PID") != str(os.getpid()):
        return None, None

    if os.environ.get("LISTEN_FDS") != "2":
        return None, None

    unix_sock = socket.socket(fileno=3)
    unix_sock.setblocking(False)
    tcp_sock = socket.socket(fileno=4)
    tcp_sock.setblocking(False)
    return unix_sock, tcp_sock


async def _run_multi(
    app: web.Application,
    *,
    sock_path: str,
    port: int | None,
    ssh_agent_port: int | None = None,
    ssh_keys_file: str | None = None,
    db_path: str | None = None,
) -> None:
    """Run the app on a Unix socket and optionally a TCP port simultaneously."""
    import asyncio

    from aiohttp.web_runner import AppRunner, SockSite, TCPSite, UnixSite

    runner = AppRunner(app, access_log=_logger)
    await runner.setup()
    ssh_server = None
    try:
        sd_unix, sd_tcp = _systemd_sockets()
        if sd_unix:
            _logger.info("Using systemd-inherited Unix socket")
            await SockSite(runner, sd_unix).start()
        else:
            path = Path(sock_path)
            try:
                mode = path.lstat().st_mode
            except FileNotFoundError:
                pass
            else:
                import socket as _socket
                import stat as _stat

                if not _stat.S_ISSOCK(mode):
                    raise RuntimeError(f"Refusing to remove non-socket path: {path}")

                probe = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
                try:
                    if probe.connect_ex(str(path)) == 0:
                        raise RuntimeError(f"Socket path already in use: {path}")
                finally:
                    probe.close()

                path.unlink()
            path.parent.mkdir(parents=True, exist_ok=True)
            _logger.info("Listening on %s", path)
            await UnixSite(runner, str(path)).start()

        if sd_tcp:
            _logger.info("Using systemd-inherited TCP socket")
            await SockSite(runner, sd_tcp).start()
        elif port is not None:
            _logger.info("Listening on 127.0.0.1:%d", port)
            await TCPSite(runner, "127.0.0.1", port).start()

        if ssh_agent_port is not None and ssh_keys_file and db_path:
            from .ssh_agent import start_ssh_agent_server

            ssh_server = await start_ssh_agent_server(
                db_path=db_path,
                keys_file=ssh_keys_file,
                host="127.0.0.1",
                port=ssh_agent_port,
            )

        await asyncio.Event().wait()  # Block until cancelled
    finally:
        if ssh_server is not None:
            ssh_server.close()
            await ssh_server.wait_closed()
        await runner.cleanup()


def main() -> None:
    """Parse CLI args and run the credential proxy."""
    import asyncio

    parser = argparse.ArgumentParser(
        prog="terok-credential-proxy",
        description="Credential injection reverse proxy for terok containers",
    )
    parser.add_argument("--socket-path", required=True, help="Unix socket path to listen on")
    parser.add_argument("--db-path", required=True, help="Path to the credential sqlite3 database")
    parser.add_argument("--routes-file", required=True, help="Path to the route config JSON")

    def _tcp_port(value: str) -> int:
        port = int(value)
        if not 1 <= port <= 65535:
            raise argparse.ArgumentTypeError("--port must be between 1 and 65535")
        return port

    parser.add_argument(
        "--port",
        type=_tcp_port,
        default=None,
        help="TCP port for container access (in addition to the Unix socket)",
    )
    parser.add_argument(
        "--ssh-agent-port",
        type=_tcp_port,
        default=None,
        help="TCP port for the SSH agent proxy (signs with host-side keys)",
    )
    parser.add_argument(
        "--ssh-keys-file",
        default=None,
        help="Path to ssh-keys.json mapping credential scopes to key file paths",
    )
    parser.add_argument(
        "--pid-file", default=None, help="Write PID to this file (for lifecycle management)"
    )
    parser.add_argument("--log-level", default="INFO", help="Logging level (default: INFO)")
    parser.add_argument("--log-file", default=None, help="Append log output to this file")
    args = parser.parse_args()

    if bool(args.ssh_agent_port) != bool(args.ssh_keys_file):
        parser.error("--ssh-agent-port and --ssh-keys-file must be provided together")

    log_level = getattr(logging, args.log_level.upper(), logging.INFO)
    log_fmt = "%(asctime)s %(name)s %(levelname)s %(message)s"
    handlers: list[logging.Handler] = []
    if args.log_file:
        handlers.append(logging.FileHandler(args.log_file))
    else:
        handlers.append(logging.StreamHandler())
    logging.basicConfig(level=log_level, format=log_fmt, handlers=handlers)

    if args.pid_file:
        import os

        Path(args.pid_file).write_text(str(os.getpid()), encoding="utf-8")

    app = _build_app(args.db_path, args.routes_file)

    # Graceful shutdown on SIGTERM
    def _handle_sigterm(*_: object) -> None:
        _logger.info("SIGTERM received, shutting down")
        raise SystemExit(0)

    signal.signal(signal.SIGTERM, _handle_sigterm)

    try:
        asyncio.run(
            _run_multi(
                app,
                sock_path=args.socket_path,
                port=args.port,
                ssh_agent_port=args.ssh_agent_port,
                ssh_keys_file=args.ssh_keys_file,
                db_path=args.db_path,
            )
        )
    except (KeyboardInterrupt, SystemExit):
        pass


if __name__ == "__main__":
    main()
