# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Vendor-aware GPU passthrough for podman containers.

The ``run.gpus`` selector names the GPU vendors a container should see:
``"all"`` (or ``true``) passes through every vendor the host detectably
supports, while ``"nvidia"`` / ``"amd"`` / ``"intel"`` — alone or as a
list — select vendors explicitly and fail loudly when the host cannot
serve one.  Several vendors in one selector simply merge their podman
args, so a mixed-GPU host can hand all of its silicon to one container.

Per vendor, the mechanism follows the vendor's own container
documentation — CDI when a host spec declares the vendor's device kind,
the documented raw-device recipe otherwise:

- **nvidia** — CDI (``nvidia.com/gpu``) when present; otherwise the
  pre-CDI Container Toolkit OCI hook (env-triggered), and as a last
  resort raw ``/dev/nvidia*`` device nodes for images that carry their
  own driver userland.
- **amd** — CDI (``amd.com/gpu``, generated by ``amd-ctk``) when
  present; otherwise the ROCm-documented ``/dev/kfd`` + ``/dev/dri``
  device pair.  The raw recipe is also what works on older podman
  releases (< 4.1) that predate CDI.
- **intel** — CDI (``intel.com/gpu``) when present; otherwise
  ``/dev/dri`` alone — the oneAPI/NEO stack needs nothing else.

The raw DRM recipes also mount ``/dev/dri/by-path`` read-only so
PCI-ordered enumeration keeps working inside the container.

A ``:N`` suffix (``"amd:1"``, ``"nvidia:0,nvidia:1"``) grants single
devices instead of a vendor's whole fleet.  On CDI hosts the index is
passed to the vendor's spec (``amd.com/gpu=1``) and means whatever the
vendor's tooling says it means.  Without CDI the grant is **best
effort**: terok orders a vendor's devices by PCI bus address — stable
across launches (and across reboots for unchanged hardware) but not
guaranteed to match ``rocm-smi``/``nvidia-smi`` numbering — mounts only
the selected device nodes, and warns on stderr.  Inside the container
the selected card enumerates as device 0.

AMD and Intel render nodes are group-gated (``render``), so those two
vendors additionally emit ``--group-add keep-groups`` — the
rootless-podman way to keep the invoking user's host groups.  That flag
is honoured by crun only; [`check_gpu_error`][terok_sandbox.runtime.gpu.check_gpu_error]
translates the runc failure into a hint.
"""

from __future__ import annotations

import json
import subprocess  # nosec B404 — podman CLI probe, matching the podman backend module
import sys
from itertools import batched
from pathlib import Path

from ..config_schema import (
    GPU_VENDORS,
    GpuGrant,
    GpuSelector,
    GpuVendor,
    normalize_gpus,
)

__all__ = [
    "GPU_VENDORS",
    "GpuConfigError",
    "GpuGrant",
    "GpuSelector",
    "GpuVendor",
    "check_gpu_available",
    "check_gpu_error",
    "detect_gpu_vendors",
    "gpu_device_addresses",
    "gpu_run_args",
    "normalize_gpus",
]

_NVIDIA_GPU_KIND = "nvidia.com/gpu"
_AMD_GPU_KIND = "amd.com/gpu"
_INTEL_GPU_KIND = "intel.com/gpu"

_KFD_DEVICE = Path("/dev/kfd")
"""AMD's compute interface — one node shared by every amdgpu-driven GPU."""
_DRI_DIR = Path("/dev/dri")
"""DRM device nodes; render nodes carry both AMD and Intel compute."""
_DRI_BY_PATH_DIR = Path("/dev/dri/by-path")
"""Stable PCI-addressed symlinks to the DRM nodes.

Mounted read-only alongside raw ``/dev/dri`` passthrough: Intel's NEO
runtime enumerates GPUs through this directory first (PCI-ordered), and
it lets multi-GPU users tell render nodes apart inside the container.
"""
_DRM_SYSFS = Path("/sys/class/drm")
_INTEL_PCI_VENDOR = "0x8086"
_AMD_PCI_VENDOR = "0x1002"

_NVIDIA_CTL_DEVICE = Path("/dev/nvidiactl")
"""Presence marker for a loaded NVIDIA kernel driver (raw fallback tier)."""
_NVIDIA_DEV_DIR = Path("/dev")
_NVIDIA_DEV_GLOB = "nvidia*"
_NVIDIA_PROC_GPUS = Path("/proc/driver/nvidia/gpus")
"""Per-GPU procfs entries, one directory per PCI address.

Each ``information`` file names the GPU's ``Device Minor`` — the ``N``
in ``/dev/nvidiaN`` — which is how the raw tier maps a PCI-ordered
device index to its node without needing ``nvidia-smi``.
"""
_NVIDIA_LEGACY_HOOK_DIRS: tuple[Path, ...] = (
    Path("/usr/share/containers/oci/hooks.d"),
    Path("/etc/containers/oci/hooks.d"),
)
_NVIDIA_LEGACY_HOOK_NAME = "oci-nvidia-hook.json"
"""The pre-CDI NVIDIA Container Toolkit OCI hook.

On hosts whose podman predates CDI (< 4.1), the toolkit integrates via
this hook instead: it triggers on the ``NVIDIA_VISIBLE_DEVICES`` env
var and injects the devices and driver userland itself.
"""

_KEEP_GROUPS_ARGS = ("--group-add", "keep-groups")
"""Keep the invoking user's host groups (``render``) in rootless containers."""

_CDI_HINT = (
    "Hint: GPU CDI configuration appears to be missing or broken.\n"
    "Ensure the vendor's container toolkit is installed and a CDI spec is\n"
    "generated (nvidia-ctk / amd-ctk / intel-cdi-specs-generator).\n"
    "See: https://podman-desktop.io/docs/podman/gpu"
)
_KEEP_GROUPS_HINT = (
    "Hint: '--group-add keep-groups' (needed for AMD/Intel GPU render nodes)\n"
    "is only supported by the crun OCI runtime.  Install crun and set\n"
    "'run.runtime: crun' in project.yml (or make crun podman's default)."
)
_NVIDIA_HOOK_HINT = (
    "Hint: the NVIDIA container hook failed to inject the GPU.  On rootless\n"
    "podman the toolkit must be configured with 'no-cgroups = true' under\n"
    "[nvidia-container-cli] in /etc/nvidia-container-runtime/config.toml\n"
    "(host admin action), and the toolkit must match the installed driver."
)

_CDI_ERROR_PATTERNS = ("cdi.k8s.io", _NVIDIA_GPU_KIND, _AMD_GPU_KIND, _INTEL_GPU_KIND, "CDI")
_KEEP_GROUPS_ERROR_PATTERNS = ("keep-groups", "keep_original_groups")
_NVIDIA_HOOK_ERROR_PATTERNS = ("nvidia-container-cli", "nvidia-container-runtime-hook")


class GpuConfigError(RuntimeError):
    """GPU misconfiguration detected before or during container launch."""

    def __init__(self, message: str, *, hint: str = _CDI_HINT) -> None:
        """Store the remediation *hint* alongside the standard error *message*."""
        self.hint = hint
        super().__init__(message)


def gpu_run_args(gpus: GpuSelector = None) -> list[str]:
    """Return ``podman run`` args passing the selected GPU grants through.

    ``"all"`` resolves against [`detect_gpu_vendors`][terok_sandbox.runtime.gpu.detect_gpu_vendors]
    and raises [`GpuConfigError`][terok_sandbox.runtime.gpu.GpuConfigError] when the host
    supports none — a project that opted into GPUs should never silently
    run without them.  Explicit grants skip detection and raise
    per-vendor when their prerequisites are missing.
    """
    if not gpus:
        return []
    cdi_kinds = _declared_cdi_kinds()
    grouped = dict.fromkeys(_resolve_all(cdi_kinds)) if gpus == "all" else _group_grants(gpus)
    args = [
        arg
        for vendor, devices in grouped.items()
        for arg in _VENDOR_ARGS[vendor](cdi_kinds, devices)
    ]
    return _dedup_pairs(args)


def _group_grants(grants: tuple[GpuGrant, ...]) -> dict[GpuVendor, tuple[int, ...] | None]:
    """Collapse normalized grants into per-vendor device selections.

    ``None`` means the whole vendor; [`normalize_gpus`][terok_sandbox.config_schema.normalize_gpus]
    already guarantees a whole-vendor grant absorbed that vendor's
    indexed ones, so each vendor is one shape or the other.
    """
    grouped: dict[GpuVendor, tuple[int, ...] | None] = {}
    for vendor, index in grants:
        if index is None:
            grouped[vendor] = None
        else:
            grouped[vendor] = (*(grouped.get(vendor) or ()), index)
    return grouped


def detect_gpu_vendors() -> frozenset[GpuVendor]:
    """Return the GPU vendors this host can pass through right now.

    A vendor counts as detected when a CDI spec declares its device
    kind, or when its fallback-recipe markers are present — NVIDIA's
    legacy OCI hook or ``/dev/nvidiactl``, AMD's ``/dev/kfd``, an
    Intel render node.
    """
    return frozenset(_resolve_all(_declared_cdi_kinds(), strict=False))


def check_gpu_available() -> bool:
    """Return ``True`` when a CDI spec declares the ``nvidia.com/gpu`` kind.

    Wizards call this to decide whether to offer the NVIDIA base image;
    the on-launch [`check_gpu_error`][terok_sandbox.runtime.gpu.check_gpu_error]
    path is the authoritative one and stays in place.  Any failure
    (missing podman, missing CDI dirs, unreadable spec) collapses to
    ``False`` so callers can treat this as a pure yes/no signal.
    """
    return _NVIDIA_GPU_KIND in _declared_cdi_kinds()


def check_gpu_error(exc: subprocess.CalledProcessError) -> None:
    """Raise [`GpuConfigError`][terok_sandbox.runtime.gpu.GpuConfigError] if *exc* looks like a GPU launch issue.

    Recognises CDI misconfiguration, the crun-only ``keep-groups``
    rejection, and legacy NVIDIA hook failures (typically the rootless
    ``no-cgroups`` requirement); does nothing when the error matches
    none of them.  Defensively
    handles both ``bytes`` and ``str`` stderr so callers that ran
    subprocess with ``text=True`` are not punished with an
    ``AttributeError`` on ``.decode``.
    """
    stderr_raw = exc.stderr or b""
    stderr = (
        stderr_raw.decode(errors="replace") if isinstance(stderr_raw, bytes) else str(stderr_raw)
    )
    hint = None
    if any(pat in stderr for pat in _KEEP_GROUPS_ERROR_PATTERNS):
        hint = _KEEP_GROUPS_HINT
    elif any(pat in stderr for pat in _NVIDIA_HOOK_ERROR_PATTERNS):
        hint = _NVIDIA_HOOK_HINT
    elif any(pat in stderr for pat in _CDI_ERROR_PATTERNS):
        hint = _CDI_HINT
    if hint is not None:
        msg = f"Container launch failed (GPU misconfiguration):\n{stderr.strip()}\n\n{hint}"
        raise GpuConfigError(msg, hint=hint) from exc


# ── Per-vendor arg recipes ─────────────────────────────────────────────────


def _nvidia_env_args(devices: tuple[int, ...] | None) -> tuple[str, ...]:
    """Toolkit visibility env — read by the CDI spec's hooks *and* by the
    legacy OCI hook, so every NVIDIA tier emits it."""
    visible = "all" if devices is None else ",".join(str(i) for i in devices)
    return ("-e", f"NVIDIA_VISIBLE_DEVICES={visible}", "-e", "NVIDIA_DRIVER_CAPABILITIES=all")


def _nvidia_args(cdi_kinds: frozenset[str], devices: tuple[int, ...] | None = None) -> list[str]:
    """NVIDIA passthrough — CDI, the legacy OCI hook, or raw device nodes.

    Tiered by how the host integrates the driver:

    1. **CDI** (podman ≥ 4.1 + ``nvidia-ctk cdi generate``) — the
       ``nvidia.com/gpu=all`` device reference, or one per selected
       device index.
    2. **Legacy OCI hook** (pre-CDI Container Toolkit installs) — the
       hook triggers on ``NVIDIA_VISIBLE_DEVICES`` and injects devices
       and driver userland itself, so the env args alone suffice —
       including for device selection, which the hook honours.
    3. **Raw device nodes** (driver loaded, no toolkit) — every
       ``/dev/nvidia*`` node, or the shared nodes plus the selected
       GPUs' nodes (best effort, PCI-bus-address order).  The image
       must then carry a driver userland (``libcuda``) matching the
       host kernel module.
    """
    env_args = _nvidia_env_args(devices)
    if _NVIDIA_GPU_KIND in cdi_kinds:
        refs: tuple[str, ...] = ("all",) if devices is None else tuple(str(i) for i in devices)
        device_args = [arg for ref in refs for arg in ("--device", f"{_NVIDIA_GPU_KIND}={ref}")]
        return [*device_args, *env_args]
    if _has_nvidia_legacy_hook():
        return list(env_args)
    if _NVIDIA_CTL_DEVICE.exists():
        if devices is None:
            nodes = sorted(_NVIDIA_DEV_DIR.glob(_NVIDIA_DEV_GLOB))
        else:
            nodes = _nvidia_raw_nodes(devices)
            _warn_best_effort("nvidia")
        device_args = [arg for node in nodes for arg in ("--device", str(node))]
        return [*device_args, *env_args]
    raise GpuConfigError(
        "run.gpus requests 'nvidia' but this host has no CDI spec declaring "
        f"'{_NVIDIA_GPU_KIND}', no legacy '{_NVIDIA_LEGACY_HOOK_NAME}' OCI hook, "
        f"and no {_NVIDIA_CTL_DEVICE} — is the nvidia kernel driver loaded?  "
        "Install the NVIDIA Container Toolkit and generate a CDI spec "
        "('nvidia-ctk cdi generate')."
    )


def _amd_args(cdi_kinds: frozenset[str], devices: tuple[int, ...] | None = None) -> list[str]:
    """AMD passthrough — CDI when generated, the ROCm device pair otherwise.

    Indexed grants without CDI mount ``/dev/kfd`` plus only the selected
    render nodes; KFD's topology still lists every GPU, but a card whose
    render node is absent cannot be driven.
    """
    if _AMD_GPU_KIND in cdi_kinds:
        refs: tuple[str, ...] = ("all",) if devices is None else tuple(str(i) for i in devices)
        device_args = [arg for ref in refs for arg in ("--device", f"{_AMD_GPU_KIND}={ref}")]
        return [*device_args, *_KEEP_GROUPS_ARGS]
    if _KFD_DEVICE.exists():
        if devices is None:
            return [
                "--device",
                str(_KFD_DEVICE),
                "--device",
                str(_DRI_DIR),
                *_dri_by_path_mount_args(),
                *_KEEP_GROUPS_ARGS,
            ]
        nodes = _selected_render_nodes("amd", _AMD_PCI_VENDOR, devices)
        _warn_best_effort("amd")
        node_args = [arg for node in nodes for arg in ("--device", str(node))]
        return ["--device", str(_KFD_DEVICE), *node_args, *_KEEP_GROUPS_ARGS]
    raise GpuConfigError(
        f"run.gpus requests 'amd' but this host has neither an '{_AMD_GPU_KIND}' "
        f"CDI spec nor {_KFD_DEVICE} — is the amdgpu kernel driver loaded?  "
        "For CDI, install the AMD Container Toolkit ('amd-ctk cdi generate')."
    )


def _intel_args(cdi_kinds: frozenset[str], devices: tuple[int, ...] | None = None) -> list[str]:
    """Intel passthrough — CDI when generated, plain ``/dev/dri`` otherwise."""
    if _INTEL_GPU_KIND in cdi_kinds:
        refs: tuple[str, ...] = ("all",) if devices is None else tuple(str(i) for i in devices)
        device_args = [arg for ref in refs for arg in ("--device", f"{_INTEL_GPU_KIND}={ref}")]
        return [*device_args, *_KEEP_GROUPS_ARGS]
    if _has_intel_render_node():
        if devices is None:
            return ["--device", str(_DRI_DIR), *_dri_by_path_mount_args(), *_KEEP_GROUPS_ARGS]
        nodes = _selected_render_nodes("intel", _INTEL_PCI_VENDOR, devices)
        _warn_best_effort("intel")
        return [*(arg for node in nodes for arg in ("--device", str(node))), *_KEEP_GROUPS_ARGS]
    raise GpuConfigError(
        f"run.gpus requests 'intel' but this host has neither an '{_INTEL_GPU_KIND}' "
        f"CDI spec nor an Intel render node under {_DRM_SYSFS} — is the i915/xe "
        "kernel driver loaded?"
    )


_VENDOR_ARGS = {"nvidia": _nvidia_args, "amd": _amd_args, "intel": _intel_args}


def _resolve_all(cdi_kinds: frozenset[str], *, strict: bool = True) -> tuple[GpuVendor, ...]:
    """Resolve the ``"all"`` selector to the vendors this host supports."""
    usable = {
        "nvidia": (
            _NVIDIA_GPU_KIND in cdi_kinds
            or _has_nvidia_legacy_hook()
            or _NVIDIA_CTL_DEVICE.exists()
        ),
        "amd": _AMD_GPU_KIND in cdi_kinds or _KFD_DEVICE.exists(),
        "intel": _INTEL_GPU_KIND in cdi_kinds or _has_intel_render_node(),
    }
    vendors = tuple(vendor for vendor in GPU_VENDORS if usable[vendor])
    if strict and not vendors:
        raise GpuConfigError(
            "run.gpus is enabled but no usable GPU support was detected on this "
            "host (no vendor CDI spec, no NVIDIA hook or /dev/nvidia*, no "
            "/dev/kfd, no Intel render node)."
        )
    return vendors


def _has_intel_render_node() -> bool:
    """True when any DRM render node belongs to an Intel GPU."""
    return any(
        _safe_read(node / "device" / "vendor").strip() == _INTEL_PCI_VENDOR
        for node in _DRM_SYSFS.glob("renderD*")
    )


# ── Best-effort device indexing (raw tiers) ────────────────────────────────


def gpu_device_addresses() -> dict[GpuVendor, tuple[str, ...]]:
    """PCI bus addresses of each vendor's GPUs, in terok index order.

    The authoritative answer to "which card does ``amd:1`` grant" on the
    raw (non-CDI) tiers: position ``N`` in a vendor's tuple is the
    device that ``vendor:N`` selects.  On CDI hosts the vendor's spec
    owns the numbering instead and this map is informational only.
    """
    try:
        nvidia = tuple(sorted(d.name for d in _NVIDIA_PROC_GPUS.iterdir()))
    except OSError:
        nvidia = ()
    return {
        "nvidia": nvidia,
        "amd": tuple(addr for addr, _ in _vendor_render_nodes(_AMD_PCI_VENDOR)),
        "intel": tuple(addr for addr, _ in _vendor_render_nodes(_INTEL_PCI_VENDOR)),
    }


def _vendor_render_nodes(pci_vendor: str) -> list[tuple[str, Path]]:
    """The vendor's ``(pci_address, /dev node)`` pairs, PCI-address ordered."""
    found = []
    for sysfs in _DRM_SYSFS.glob("renderD*"):
        if _safe_read(sysfs / "device" / "vendor").strip() != pci_vendor:
            continue
        found.append((_pci_address(sysfs), _DRI_DIR / sysfs.name))
    return sorted(found)


def _pci_address(sysfs_node: Path) -> str:
    """PCI bus address of a DRM sysfs node (its ``device`` symlink target)."""
    try:
        return (sysfs_node / "device").resolve().name
    except OSError:
        return sysfs_node.name


def _selected_render_nodes(
    vendor: GpuVendor, pci_vendor: str, devices: tuple[int, ...]
) -> list[Path]:
    """Resolve device indices to render nodes, failing loudly out of range."""
    nodes = _vendor_render_nodes(pci_vendor)
    if bad := [i for i in devices if i >= len(nodes)]:
        available = ", ".join(f"{vendor}:{i}={addr}" for i, (addr, _) in enumerate(nodes))
        raise GpuConfigError(
            f"run.gpus selects {vendor} device(s) {bad} but this host has "
            f"{len(nodes)} {vendor} device(s)" + (f": {available}" if available else ".")
        )
    return [nodes[i][1] for i in devices]


def _nvidia_raw_nodes(devices: tuple[int, ...]) -> list[Path]:
    """Shared NVIDIA nodes plus the selected GPUs' nodes (raw tier).

    Per-GPU nodes are ``/dev/nvidia<minor>``; everything else matching
    the glob (``nvidiactl``, ``nvidia-uvm``, …) is shared and always
    granted.
    """
    minors = _nvidia_minors_by_pci_order()
    if bad := [i for i in devices if i >= len(minors)]:
        raise GpuConfigError(
            f"run.gpus selects nvidia device(s) {bad} but this host has "
            f"{len(minors)} NVIDIA device(s) (see /proc/driver/nvidia/gpus)."
        )
    shared = [
        node
        for node in sorted(_NVIDIA_DEV_DIR.glob(_NVIDIA_DEV_GLOB))
        if not node.name.removeprefix("nvidia").isdigit()
    ]
    return shared + [_NVIDIA_DEV_DIR / f"nvidia{minors[i]}" for i in devices]


def _nvidia_minors_by_pci_order() -> list[int]:
    """Device minors of the host's NVIDIA GPUs, PCI-bus-address ordered.

    Parsed from ``/proc/driver/nvidia/gpus/<pci>/information`` — present
    whenever the kernel driver is loaded, so the raw tier needs no
    vendor tools for the mapping.
    """
    minors: list[int] = []
    try:
        gpu_dirs = sorted(_NVIDIA_PROC_GPUS.iterdir())
    except OSError:
        gpu_dirs = []
    for gpu_dir in gpu_dirs:
        for line in _safe_read(gpu_dir / "information").splitlines():
            key, _, value = line.partition(":")
            if key.strip() == "Device Minor" and value.strip().isdigit():
                minors.append(int(value.strip()))
                break
    if not minors:
        raise GpuConfigError(
            "run.gpus selects an nvidia device by index, but the device-minor "
            f"map under {_NVIDIA_PROC_GPUS} is unavailable — cannot identify "
            "the device nodes.  Grant the whole vendor ('nvidia') instead, or "
            "install the NVIDIA Container Toolkit and generate a CDI spec."
        )
    return minors


def _warn_best_effort(vendor: GpuVendor) -> None:
    """One stderr notice per raw indexed grant — degraded, not denied."""
    carrot = " (which also lifts the baked-driver requirement)" if vendor == "nvidia" else ""
    print(
        f"WARNING: '{vendor}' GPU device selection without CDI is best-effort: "
        "terok orders devices by PCI bus address, which may differ from the "
        "vendor tools' numbering.  Install the vendor's CDI spec for "
        f"authoritative device mapping{carrot}.",
        file=sys.stderr,
    )


def _has_nvidia_legacy_hook() -> bool:
    """True when the pre-CDI NVIDIA Container Toolkit OCI hook is installed."""
    return any((d / _NVIDIA_LEGACY_HOOK_NAME).is_file() for d in _NVIDIA_LEGACY_HOOK_DIRS)


def _dri_by_path_mount_args() -> list[str]:
    """Read-only ``/dev/dri/by-path`` mount for the raw DRM recipes.

    ``--device /dev/dri`` replicates the device nodes but not the
    PCI-addressed symlinks; mounting them keeps Intel NEO's primary
    (PCI-ordered) enumeration path working and makes multi-GPU device
    identity legible inside the container.  Skipped when the host has
    no such directory.
    """
    if not _DRI_BY_PATH_DIR.is_dir():
        return []
    return ["-v", f"{_DRI_BY_PATH_DIR}:{_DRI_BY_PATH_DIR}:ro"]


def _dedup_pairs(args: list[str]) -> list[str]:
    """Drop repeated ``(flag, value)`` pairs, keeping first-seen order.

    Vendors sharing a recipe element (AMD and Intel both mount
    ``/dev/dri`` and keep groups) must not emit it twice.
    """
    return [arg for pair in dict.fromkeys(batched(args, 2)) for arg in pair]


# ── CDI spec probing ───────────────────────────────────────────────────────


_CDI_DEFAULT_DIRS: tuple[Path, ...] = (Path("/etc/cdi"), Path("/var/run/cdi"))


def _declared_cdi_kinds() -> frozenset[str]:
    """Return the vendor device kinds declared by the host's CDI specs.

    One podman round trip serves every vendor probe in a launch, so the
    per-vendor recipes and the ``"all"`` resolver share its result.
    """
    specs = [_safe_read(p) for p in _cdi_spec_paths()]
    return frozenset(
        kind
        for kind in (_NVIDIA_GPU_KIND, _AMD_GPU_KIND, _INTEL_GPU_KIND)
        if any(kind in spec for spec in specs)
    )


def _cdi_spec_paths() -> list[Path]:
    """Return CDI spec file paths podman is configured to scan.

    Asks podman first (so a custom ``cdi_spec_dirs`` in
    ``containers.conf`` is honoured) and falls back to the documented
    default directories when podman is absent or its info template
    doesn't expose ``Host.CDISpecs`` (older versions).
    """
    try:
        proc = subprocess.run(  # nosec B603 B607 — podman CLI invocation matches existing pattern in this module
            ["podman", "info", "--format", "{{json .Host.CDISpecs}}"],
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
        listed = json.loads(proc.stdout or "null") or []
        if listed:
            return [Path(p) for p in listed]
    except (
        FileNotFoundError,
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
        json.JSONDecodeError,
    ):
        pass
    return [f for d in _CDI_DEFAULT_DIRS if d.is_dir() for f in d.iterdir() if f.is_file()]


def _safe_read(path: Path) -> str:
    try:
        return path.read_text(errors="replace")
    except OSError:
        return ""
