# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Vendor-aware GPU passthrough for podman containers.

The ``run.gpus`` selector names the GPU vendors a container should see:
``"all"`` (or ``true``) passes through every vendor the host detectably
supports, while ``"nvidia"`` / ``"amd"`` / ``"intel"`` — alone or as a
list — select vendors explicitly and fail loudly when the host cannot
serve one.  Several vendors in one selector simply merge their podman
args, so a mixed-GPU host can hand all of its silicon to one container.

Per vendor, the mechanism follows the vendor's own container
documentation — CDI when a host spec declares the vendor's device kind,
the documented raw-device recipe otherwise:

- **nvidia** — CDI only (``nvidia.com/gpu``): the NVIDIA userland is
  injected by the Container Toolkit's CDI spec, so there is no
  meaningful raw fallback.
- **amd** — CDI (``amd.com/gpu``, generated by ``amd-ctk``) when
  present; otherwise the ROCm-documented ``/dev/kfd`` + ``/dev/dri``
  device pair.  The raw recipe is also what works on older podman
  releases (< 4.1) that predate CDI.
- **intel** — CDI (``intel.com/gpu``) when present; otherwise
  ``/dev/dri`` alone — the oneAPI/NEO stack needs nothing else.

AMD and Intel render nodes are group-gated (``render``), so those two
vendors additionally emit ``--group-add keep-groups`` — the
rootless-podman way to keep the invoking user's host groups.  That flag
is honoured by crun only; [`check_gpu_error`][terok_sandbox.runtime.gpu.check_gpu_error]
translates the runc failure into a hint.
"""

from __future__ import annotations

import json
import subprocess  # nosec B404 — podman CLI probe, matching the podman backend module
from itertools import batched
from pathlib import Path

from ..config_schema import (
    GPU_VENDORS,
    GpuSelector,
    GpuVendor,
    normalize_gpus,
)

__all__ = [
    "GPU_VENDORS",
    "GpuConfigError",
    "GpuSelector",
    "GpuVendor",
    "check_gpu_available",
    "check_gpu_error",
    "detect_gpu_vendors",
    "gpu_run_args",
    "normalize_gpus",
]

_NVIDIA_GPU_KIND = "nvidia.com/gpu"
_AMD_GPU_KIND = "amd.com/gpu"
_INTEL_GPU_KIND = "intel.com/gpu"

_KFD_DEVICE = Path("/dev/kfd")
"""AMD's compute interface — one node shared by every amdgpu-driven GPU."""
_DRI_DIR = Path("/dev/dri")
"""DRM device nodes; render nodes carry both AMD and Intel compute."""
_DRM_SYSFS = Path("/sys/class/drm")
_INTEL_PCI_VENDOR = "0x8086"

_KEEP_GROUPS_ARGS = ("--group-add", "keep-groups")
"""Keep the invoking user's host groups (``render``) in rootless containers."""

_CDI_HINT = (
    "Hint: GPU CDI configuration appears to be missing or broken.\n"
    "Ensure the vendor's container toolkit is installed and a CDI spec is\n"
    "generated (nvidia-ctk / amd-ctk / intel-cdi-specs-generator).\n"
    "See: https://podman-desktop.io/docs/podman/gpu"
)
_KEEP_GROUPS_HINT = (
    "Hint: '--group-add keep-groups' (needed for AMD/Intel GPU render nodes)\n"
    "is only supported by the crun OCI runtime.  Install crun and set\n"
    "'run.runtime: crun' in project.yml (or make crun podman's default)."
)

_CDI_ERROR_PATTERNS = ("cdi.k8s.io", _NVIDIA_GPU_KIND, _AMD_GPU_KIND, _INTEL_GPU_KIND, "CDI")
_KEEP_GROUPS_ERROR_PATTERNS = ("keep-groups", "keep_original_groups")


class GpuConfigError(RuntimeError):
    """GPU misconfiguration detected before or during container launch."""

    def __init__(self, message: str, *, hint: str = _CDI_HINT) -> None:
        """Store the remediation *hint* alongside the standard error *message*."""
        self.hint = hint
        super().__init__(message)


def gpu_run_args(gpus: GpuSelector = None) -> list[str]:
    """Return ``podman run`` args passing the selected GPU vendors through.

    ``"all"`` resolves against [`detect_gpu_vendors`][terok_sandbox.runtime.gpu.detect_gpu_vendors]
    and raises [`GpuConfigError`][terok_sandbox.runtime.gpu.GpuConfigError] when the host
    supports none — a project that opted into GPUs should never silently
    run without them.  Explicit vendors skip detection and raise
    per-vendor when their prerequisites are missing.
    """
    if not gpus:
        return []
    cdi_kinds = _declared_cdi_kinds()
    vendors = _resolve_all(cdi_kinds) if gpus == "all" else gpus
    args = [arg for vendor in vendors for arg in _VENDOR_ARGS[vendor](cdi_kinds)]
    return _dedup_pairs(args)


def detect_gpu_vendors() -> frozenset[GpuVendor]:
    """Return the GPU vendors this host can pass through right now.

    A vendor counts as detected when a CDI spec declares its device
    kind, or — for AMD and Intel — when the raw-recipe device nodes
    are present (``/dev/kfd``; an Intel render node).  NVIDIA has no
    raw recipe, so only its CDI spec counts.
    """
    return frozenset(_resolve_all(_declared_cdi_kinds(), strict=False))


def check_gpu_available() -> bool:
    """Return ``True`` when a CDI spec declares the ``nvidia.com/gpu`` kind.

    Wizards call this to decide whether to offer the NVIDIA base image;
    the on-launch [`check_gpu_error`][terok_sandbox.runtime.gpu.check_gpu_error]
    path is the authoritative one and stays in place.  Any failure
    (missing podman, missing CDI dirs, unreadable spec) collapses to
    ``False`` so callers can treat this as a pure yes/no signal.
    """
    return _NVIDIA_GPU_KIND in _declared_cdi_kinds()


def check_gpu_error(exc: subprocess.CalledProcessError) -> None:
    """Raise [`GpuConfigError`][terok_sandbox.runtime.gpu.GpuConfigError] if *exc* looks like a GPU launch issue.

    Recognises CDI misconfiguration and the crun-only ``keep-groups``
    rejection; does nothing when the error matches neither.  Defensively
    handles both ``bytes`` and ``str`` stderr so callers that ran
    subprocess with ``text=True`` are not punished with an
    ``AttributeError`` on ``.decode``.
    """
    stderr_raw = exc.stderr or b""
    stderr = (
        stderr_raw.decode(errors="replace") if isinstance(stderr_raw, bytes) else str(stderr_raw)
    )
    hint = None
    if any(pat in stderr for pat in _KEEP_GROUPS_ERROR_PATTERNS):
        hint = _KEEP_GROUPS_HINT
    elif any(pat in stderr for pat in _CDI_ERROR_PATTERNS):
        hint = _CDI_HINT
    if hint is not None:
        msg = f"Container launch failed (GPU misconfiguration):\n{stderr.strip()}\n\n{hint}"
        raise GpuConfigError(msg, hint=hint) from exc


# ── Per-vendor arg recipes ─────────────────────────────────────────────────


def _nvidia_args(cdi_kinds: frozenset[str]) -> list[str]:
    """NVIDIA passthrough — CDI device plus the toolkit's visibility env."""
    if _NVIDIA_GPU_KIND not in cdi_kinds:
        raise GpuConfigError(
            "run.gpus requests 'nvidia' but no CDI spec on this host declares "
            f"'{_NVIDIA_GPU_KIND}'.  Install the NVIDIA Container Toolkit and "
            "generate one ('nvidia-ctk cdi generate')."
        )
    return [
        "--device",
        f"{_NVIDIA_GPU_KIND}=all",
        "-e",
        "NVIDIA_VISIBLE_DEVICES=all",
        "-e",
        "NVIDIA_DRIVER_CAPABILITIES=all",
    ]


def _amd_args(cdi_kinds: frozenset[str]) -> list[str]:
    """AMD passthrough — CDI when generated, the ROCm device pair otherwise."""
    if _AMD_GPU_KIND in cdi_kinds:
        return ["--device", f"{_AMD_GPU_KIND}=all", *_KEEP_GROUPS_ARGS]
    if _KFD_DEVICE.exists():
        return ["--device", str(_KFD_DEVICE), "--device", str(_DRI_DIR), *_KEEP_GROUPS_ARGS]
    raise GpuConfigError(
        f"run.gpus requests 'amd' but this host has neither an '{_AMD_GPU_KIND}' "
        f"CDI spec nor {_KFD_DEVICE} — is the amdgpu kernel driver loaded?  "
        "For CDI, install the AMD Container Toolkit ('amd-ctk cdi generate')."
    )


def _intel_args(cdi_kinds: frozenset[str]) -> list[str]:
    """Intel passthrough — CDI when generated, plain ``/dev/dri`` otherwise."""
    if _INTEL_GPU_KIND in cdi_kinds:
        return ["--device", f"{_INTEL_GPU_KIND}=all", *_KEEP_GROUPS_ARGS]
    if _has_intel_render_node():
        return ["--device", str(_DRI_DIR), *_KEEP_GROUPS_ARGS]
    raise GpuConfigError(
        f"run.gpus requests 'intel' but this host has neither an '{_INTEL_GPU_KIND}' "
        f"CDI spec nor an Intel render node under {_DRM_SYSFS} — is the i915/xe "
        "kernel driver loaded?"
    )


_VENDOR_ARGS = {"nvidia": _nvidia_args, "amd": _amd_args, "intel": _intel_args}


def _resolve_all(cdi_kinds: frozenset[str], *, strict: bool = True) -> tuple[GpuVendor, ...]:
    """Resolve the ``"all"`` selector to the vendors this host supports."""
    usable = {
        "nvidia": _NVIDIA_GPU_KIND in cdi_kinds,
        "amd": _AMD_GPU_KIND in cdi_kinds or _KFD_DEVICE.exists(),
        "intel": _INTEL_GPU_KIND in cdi_kinds or _has_intel_render_node(),
    }
    vendors = tuple(vendor for vendor in GPU_VENDORS if usable[vendor])
    if strict and not vendors:
        raise GpuConfigError(
            "run.gpus is enabled but no usable GPU support was detected on this "
            "host (no vendor CDI spec, no /dev/kfd, no Intel render node)."
        )
    return vendors


def _has_intel_render_node() -> bool:
    """True when any DRM render node belongs to an Intel GPU."""
    return any(
        _safe_read(node / "device" / "vendor").strip() == _INTEL_PCI_VENDOR
        for node in _DRM_SYSFS.glob("renderD*")
    )


def _dedup_pairs(args: list[str]) -> list[str]:
    """Drop repeated ``(flag, value)`` pairs, keeping first-seen order.

    Vendors sharing a recipe element (AMD and Intel both mount
    ``/dev/dri`` and keep groups) must not emit it twice.
    """
    return [arg for pair in dict.fromkeys(batched(args, 2)) for arg in pair]


# ── CDI spec probing ───────────────────────────────────────────────────────


_CDI_DEFAULT_DIRS: tuple[Path, ...] = (Path("/etc/cdi"), Path("/var/run/cdi"))


def _declared_cdi_kinds() -> frozenset[str]:
    """Return the vendor device kinds declared by the host's CDI specs.

    One podman round trip serves every vendor probe in a launch, so the
    per-vendor recipes and the ``"all"`` resolver share its result.
    """
    specs = [_safe_read(p) for p in _cdi_spec_paths()]
    return frozenset(
        kind
        for kind in (_NVIDIA_GPU_KIND, _AMD_GPU_KIND, _INTEL_GPU_KIND)
        if any(kind in spec for spec in specs)
    )


def _cdi_spec_paths() -> list[Path]:
    """Return CDI spec file paths podman is configured to scan.

    Asks podman first (so a custom ``cdi_spec_dirs`` in
    ``containers.conf`` is honoured) and falls back to the documented
    default directories when podman is absent or its info template
    doesn't expose ``Host.CDISpecs`` (older versions).
    """
    try:
        proc = subprocess.run(  # nosec B603 B607 — podman CLI invocation matches existing pattern in this module
            ["podman", "info", "--format", "{{json .Host.CDISpecs}}"],
            capture_output=True,
            text=True,
            timeout=5,
            check=True,
        )
        listed = json.loads(proc.stdout or "null") or []
        if listed:
            return [Path(p) for p in listed]
    except (
        FileNotFoundError,
        subprocess.CalledProcessError,
        subprocess.TimeoutExpired,
        json.JSONDecodeError,
    ):
        pass
    return [f for d in _CDI_DEFAULT_DIRS if d.is_dir() for f in d.iterdir() if f.is_file()]


def _safe_read(path: Path) -> str:
    try:
        return path.read_text(errors="replace")
    except OSError:
        return ""
