# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Credential proxy — HTTP-over-Unix-socket reverse proxy with secret injection.

This module has **zero terok imports**.  It is a self-contained security
component: a standalone daemon that listens on a Unix socket, validates
phantom tokens against a sqlite3 database, injects real credentials from
the same database, and forwards requests to upstream API servers.

Task containers see only phantom API keys (worthless outside the proxy).
Real secrets never enter the container filesystem or environment.

Startup::

    terok-credential-proxy \\
        --socket-path /run/terok/credential-proxy.sock \\
        --db-path ~/.local/share/terok/proxy/credentials.db \\
        --routes-file ~/.local/share/terok/proxy/routes.json

Route config (JSON, generated by terok-agent from YAML registry)::

    {
      "claude": {
        "upstream": "https://api.anthropic.com",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer "
      }
    }
"""

from __future__ import annotations

import argparse
import json
import logging
import signal
import sqlite3
from pathlib import Path

from aiohttp import ClientSession, web

_logger = logging.getLogger("terok-credential-proxy")

# Typed app keys (avoids NotAppKeyWarning on aiohttp >= 3.9)
_KEY_ROUTES = web.AppKey("routes", "_RouteTable")
_KEY_TOKEN_DB = web.AppKey("token_db", "_TokenDB")
_KEY_CLIENT = web.AppKey("client_session", ClientSession)

# ---------------------------------------------------------------------------
# Route + credential loading (inlined, no terok imports)
# ---------------------------------------------------------------------------


class _RouteTable:
    """Path-prefix routing table loaded from a JSON file."""

    def __init__(self, routes_path: str) -> None:
        with open(routes_path) as f:
            self._routes: dict[str, dict] = json.load(f)
        for prefix, cfg in self._routes.items():
            if "upstream" not in cfg:
                raise ValueError(f"Route '{prefix}' missing required 'upstream' field")

    def resolve(self, path: str) -> tuple[str | None, str, dict]:
        """Parse ``/{prefix}/{rest}`` and return ``(prefix, rest, route_config)``.

        Returns ``(None, path, {})`` if no route matches.
        """
        parts = path.lstrip("/").split("/", 1)
        prefix = parts[0] if parts else ""
        rest = f"/{parts[1]}" if len(parts) > 1 else "/"
        route = self._routes.get(prefix)
        if route is None:
            return None, path, {}
        return prefix, rest, route


class _TokenDB:
    """Read-only sqlite3 accessor for phantom token lookups and credential loading."""

    def __init__(self, db_path: str) -> None:
        # check_same_thread=False is safe: this is a read-only accessor and
        # aiohttp runs handlers in a single event loop thread.
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.execute("PRAGMA journal_mode=WAL")

    def lookup_token(self, token: str) -> dict | None:
        """Return ``{project, task, credential_set}`` or ``None``."""
        row = self._conn.execute(
            "SELECT project, task, credential_set FROM proxy_tokens WHERE token = ?",
            (token,),
        ).fetchone()
        if row is None:
            return None
        return {"project": row[0], "task": row[1], "credential_set": row[2]}

    def load_credential(self, credential_set: str, provider: str) -> dict | None:
        """Return parsed credential data dict, or ``None``."""
        row = self._conn.execute(
            "SELECT data FROM credentials WHERE credential_set = ? AND provider = ?",
            (credential_set, provider),
        ).fetchone()
        return json.loads(row[0]) if row else None

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()

    def __del__(self) -> None:
        """Best-effort close on garbage collection."""
        try:
            self._conn.close()
        except Exception:  # noqa: BLE001
            pass


# ---------------------------------------------------------------------------
# Auth extraction helpers
# ---------------------------------------------------------------------------

_AUTH_HEADERS = ("authorization", "x-api-key")


def _extract_phantom_token(request: web.Request) -> str | None:
    """Extract a phantom token from Authorization or X-Api-Key headers."""
    for header in _AUTH_HEADERS:
        value = request.headers.get(header)
        if not value:
            continue
        # Strip "Bearer ", "token ", etc. prefixes
        if " " in value:
            return value.split(None, 1)[1]
        return value
    return None


# ---------------------------------------------------------------------------
# Request handler
# ---------------------------------------------------------------------------


async def _handle_request(request: web.Request) -> web.StreamResponse:
    """Route, authenticate, inject credentials, and forward to upstream."""
    routes: _RouteTable = request.app[_KEY_ROUTES]
    token_db: _TokenDB = request.app[_KEY_TOKEN_DB]

    # 1. Route by path prefix
    prefix, rest, route = routes.resolve(request.path)
    if prefix is None:
        return web.Response(status=404, text="Unknown route")

    # 2. Validate phantom token
    phantom = _extract_phantom_token(request)
    if not phantom:
        return web.Response(status=401, text="Missing authentication")

    token_info = token_db.lookup_token(phantom)
    if token_info is None:
        return web.Response(status=401, text="Invalid token")

    # 3. Load real credential
    cred = token_db.load_credential(token_info["credential_set"], prefix)
    if cred is None:
        _logger.warning(
            "No credential for provider %r in set %r", prefix, token_info["credential_set"]
        )
        return web.Response(status=502, text="Credential not configured for this provider")

    # Determine the real auth value and header based on credential type.
    # OAuth tokens use "Authorization: Bearer <token>"; API keys use the
    # route-configured header (e.g. "x-api-key: <key>").
    # Legacy rows without "type" are detected by the presence of "access_token".
    cred_type = cred.get("type", "")
    is_oauth = cred_type == "oauth" or (not cred_type and "access_token" in cred)
    if is_oauth:
        real_token = cred.get("access_token")
        if not real_token:
            _logger.error("Credential for %r is OAuth but missing access_token", prefix)
            return web.Response(status=502, text="Credential misconfigured")
        auth_header = "Authorization"
        auth_prefix = "Bearer "
    else:
        real_token = cred.get("token") or cred.get("key")
        if not real_token:
            _logger.error("Credential for %r has no usable token field", prefix)
            return web.Response(status=502, text="Credential misconfigured")
        auth_header = route.get("auth_header", "Authorization")
        auth_prefix = route.get("auth_prefix", "Bearer ")
        # "dynamic" means auto-detect — for API keys, use x-api-key
        if auth_header == "dynamic":
            auth_header = "x-api-key"
            auth_prefix = ""

    # 4. Build upstream request — strip phantom auth, inject real auth
    upstream_url = route["upstream"].rstrip("/") + rest
    if request.query_string:
        upstream_url += f"?{request.query_string}"

    headers = {
        k: v
        for k, v in request.headers.items()
        if k.lower() not in _AUTH_HEADERS and k.lower() != "host"
    }
    headers[auth_header] = f"{auth_prefix}{real_token}"

    # 5. Forward and stream response
    session: ClientSession = request.app[_KEY_CLIENT]
    try:
        async with session.request(
            request.method,
            upstream_url,
            headers=headers,
            data=request.content if request.can_read_body else None,
            allow_redirects=False,
        ) as upstream:
            # Build response with upstream status + headers
            resp = web.StreamResponse(status=upstream.status)
            # Forward selected headers
            for hdr in ("content-type", "transfer-encoding", "cache-control"):
                val = upstream.headers.get(hdr)
                if val:
                    resp.headers[hdr] = val
            await resp.prepare(request)

            async for chunk in upstream.content.iter_any():
                await resp.write(chunk)
            await resp.write_eof()
            return resp
    except Exception as exc:
        _logger.error("Upstream request to %s failed: %s", prefix, exc)
        return web.Response(status=502, text="Upstream request failed")


# ---------------------------------------------------------------------------
# Application lifecycle
# ---------------------------------------------------------------------------


async def _on_startup(app: web.Application) -> None:
    """Create the shared HTTP client session."""
    app[_KEY_CLIENT] = ClientSession()


async def _on_cleanup(app: web.Application) -> None:
    """Close client session and token DB."""
    await app[_KEY_CLIENT].close()
    app[_KEY_TOKEN_DB].close()


def _build_app(db_path: str, routes_path: str) -> web.Application:
    """Construct the aiohttp application."""
    app = web.Application()
    app[_KEY_ROUTES] = _RouteTable(routes_path)
    app[_KEY_TOKEN_DB] = _TokenDB(db_path)
    app.on_startup.append(_on_startup)
    app.on_cleanup.append(_on_cleanup)
    app.router.add_route("*", "/{tail:.*}", _handle_request)
    return app


def _systemd_socket():
    """Return the inherited socket from systemd activation, or ``None``.

    Implements the ``sd_listen_fds(3)`` protocol: if ``LISTEN_FDS=1`` and
    ``LISTEN_PID`` matches the current process, file descriptor 3 is an
    already-listening socket passed by systemd.
    """
    import os
    import socket as _socket

    if os.environ.get("LISTEN_FDS") == "1" and os.environ.get("LISTEN_PID") == str(os.getpid()):
        sock = _socket.socket(fileno=3)
        sock.setblocking(False)
        return sock
    return None


def main() -> None:
    """Parse CLI args and run the credential proxy."""
    parser = argparse.ArgumentParser(
        prog="terok-credential-proxy",
        description="Credential injection reverse proxy for terok containers",
    )
    parser.add_argument("--socket-path", required=True, help="Unix socket path to listen on")
    parser.add_argument("--db-path", required=True, help="Path to the credential sqlite3 database")
    parser.add_argument("--routes-file", required=True, help="Path to the route config JSON")
    parser.add_argument(
        "--pid-file", default=None, help="Write PID to this file (for lifecycle management)"
    )
    parser.add_argument("--log-level", default="INFO", help="Logging level (default: INFO)")
    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    if args.pid_file:
        import os

        Path(args.pid_file).write_text(str(os.getpid()), encoding="utf-8")

    app = _build_app(args.db_path, args.routes_file)

    # Graceful shutdown on SIGTERM
    def _handle_sigterm(*_: object) -> None:
        _logger.info("SIGTERM received, shutting down")
        raise SystemExit(0)

    signal.signal(signal.SIGTERM, _handle_sigterm)

    sd_sock = _systemd_socket()
    if sd_sock:
        _logger.info("Using systemd-inherited socket")
        web.run_app(app, sock=sd_sock, print=lambda *_: None)
    else:
        sock_path = Path(args.socket_path)
        sock_path.unlink(missing_ok=True)
        sock_path.parent.mkdir(parents=True, exist_ok=True)
        _logger.info("Listening on %s", sock_path)
        web.run_app(app, path=str(sock_path), print=lambda *_: None)


if __name__ == "__main__":
    main()
