# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Credential proxy — HTTP-over-Unix-socket reverse proxy with secret injection.

This module has **zero terok imports**.  It is a self-contained security
component: a standalone daemon that listens on a Unix socket, validates
phantom tokens against a sqlite3 database, injects real credentials from
the same database, and forwards requests to upstream API servers.

Task containers see only phantom API keys (worthless outside the proxy).
Real secrets never enter the container filesystem or environment.

Startup::

    terok-credential-proxy \\
        --socket-path /run/terok/credential-proxy.sock \\
        --db-path ~/.local/share/terok/proxy/credentials.db \\
        --routes-file ~/.local/share/terok/proxy/routes.json

Route config (JSON, generated by terok-agent from YAML registry)::

    {
      "claude": {
        "upstream": "https://api.anthropic.com",
        "auth_header": "Authorization",
        "auth_prefix": "Bearer "
      }
    }
"""

from __future__ import annotations

import argparse
import json
import logging
import signal
import sqlite3
from pathlib import Path

from aiohttp import ClientSession, web

_logger = logging.getLogger("terok-credential-proxy")

# ---------------------------------------------------------------------------
# Route + credential loading (inlined, no terok imports)
# ---------------------------------------------------------------------------


class _RouteTable:
    """Path-prefix routing table loaded from a JSON file."""

    def __init__(self, routes_path: str) -> None:
        with open(routes_path) as f:
            self._routes: dict[str, dict] = json.load(f)

    def resolve(self, path: str) -> tuple[str | None, str, dict]:
        """Parse ``/{prefix}/{rest}`` and return ``(prefix, rest, route_config)``.

        Returns ``(None, path, {})`` if no route matches.
        """
        parts = path.lstrip("/").split("/", 1)
        prefix = parts[0] if parts else ""
        rest = f"/{parts[1]}" if len(parts) > 1 else "/"
        route = self._routes.get(prefix)
        if route is None:
            return None, path, {}
        return prefix, rest, route


class _TokenDB:
    """Read-only sqlite3 accessor for phantom token lookups and credential loading."""

    def __init__(self, db_path: str) -> None:
        self._conn = sqlite3.connect(db_path, check_same_thread=False)
        self._conn.execute("PRAGMA journal_mode=WAL")

    def lookup_token(self, token: str) -> dict | None:
        """Return ``{project, task, credential_set}`` or ``None``."""
        row = self._conn.execute(
            "SELECT project, task, credential_set FROM proxy_tokens WHERE token = ?",
            (token,),
        ).fetchone()
        if row is None:
            return None
        return {"project": row[0], "task": row[1], "credential_set": row[2]}

    def load_credential(self, credential_set: str, provider: str) -> dict | None:
        """Return parsed credential data dict, or ``None``."""
        row = self._conn.execute(
            "SELECT data FROM credentials WHERE credential_set = ? AND provider = ?",
            (credential_set, provider),
        ).fetchone()
        return json.loads(row[0]) if row else None

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()


# ---------------------------------------------------------------------------
# Auth extraction helpers
# ---------------------------------------------------------------------------

_AUTH_HEADERS = ("authorization", "x-api-key")


def _extract_phantom_token(request: web.Request) -> str | None:
    """Extract a phantom token from Authorization or X-Api-Key headers."""
    for header in _AUTH_HEADERS:
        value = request.headers.get(header)
        if not value:
            continue
        # Strip "Bearer ", "token ", etc. prefixes
        if " " in value:
            return value.split(None, 1)[1]
        return value
    return None


# ---------------------------------------------------------------------------
# Request handler
# ---------------------------------------------------------------------------


async def _handle_request(request: web.Request) -> web.StreamResponse:
    """Route, authenticate, inject credentials, and forward to upstream."""
    routes: _RouteTable = request.app["routes"]
    token_db: _TokenDB = request.app["token_db"]

    # 1. Route by path prefix
    prefix, rest, route = routes.resolve(request.path)
    if prefix is None:
        return web.Response(status=404, text="Unknown route")

    # 2. Validate phantom token
    phantom = _extract_phantom_token(request)
    if not phantom:
        return web.Response(status=401, text="Missing authentication")

    token_info = token_db.lookup_token(phantom)
    if token_info is None:
        return web.Response(status=401, text="Invalid token")

    # 3. Load real credential
    cred = token_db.load_credential(token_info["credential_set"], prefix)
    if cred is None:
        return web.Response(status=502, text=f"No credential stored for provider '{prefix}'")

    # Determine the real auth value
    real_token = cred.get("access_token") or cred.get("token") or cred.get("key") or ""
    auth_header = route.get("auth_header", "Authorization")
    auth_prefix = route.get("auth_prefix", "Bearer ")

    # 4. Build upstream request — strip phantom auth, inject real auth
    upstream_url = route["upstream"].rstrip("/") + rest
    if request.query_string:
        upstream_url += f"?{request.query_string}"

    headers = {
        k: v
        for k, v in request.headers.items()
        if k.lower() not in _AUTH_HEADERS and k.lower() != "host"
    }
    headers[auth_header] = f"{auth_prefix}{real_token}"

    # 5. Forward and stream response
    session: ClientSession = request.app["client_session"]
    try:
        async with session.request(
            request.method,
            upstream_url,
            headers=headers,
            data=request.content if request.can_read_body else None,
            allow_redirects=False,
        ) as upstream:
            # Build response with upstream status + headers
            resp = web.StreamResponse(status=upstream.status)
            # Forward selected headers
            for hdr in ("content-type", "transfer-encoding", "cache-control"):
                val = upstream.headers.get(hdr)
                if val:
                    resp.headers[hdr] = val
            await resp.prepare(request)

            async for chunk in upstream.content.iter_any():
                await resp.write(chunk)
            await resp.write_eof()
            return resp
    except Exception as exc:
        _logger.error("Upstream request failed: %s", exc)
        return web.Response(status=502, text=f"Upstream error: {exc}")


# ---------------------------------------------------------------------------
# Application lifecycle
# ---------------------------------------------------------------------------


async def _on_startup(app: web.Application) -> None:
    """Create the shared HTTP client session."""
    app["client_session"] = ClientSession()


async def _on_cleanup(app: web.Application) -> None:
    """Close client session and token DB."""
    await app["client_session"].close()
    app["token_db"].close()


def _build_app(db_path: str, routes_path: str) -> web.Application:
    """Construct the aiohttp application."""
    app = web.Application()
    app["routes"] = _RouteTable(routes_path)
    app["token_db"] = _TokenDB(db_path)
    app.on_startup.append(_on_startup)
    app.on_cleanup.append(_on_cleanup)
    app.router.add_route("*", "/{tail:.*}", _handle_request)
    return app


def main() -> None:
    """Parse CLI args and run the credential proxy."""
    parser = argparse.ArgumentParser(
        prog="terok-credential-proxy",
        description="Credential injection reverse proxy for terok containers",
    )
    parser.add_argument("--socket-path", required=True, help="Unix socket path to listen on")
    parser.add_argument("--db-path", required=True, help="Path to the credential sqlite3 database")
    parser.add_argument("--routes-file", required=True, help="Path to the route config JSON")
    parser.add_argument("--log-level", default="INFO", help="Logging level (default: INFO)")
    args = parser.parse_args()

    logging.basicConfig(
        level=getattr(logging, args.log_level.upper(), logging.INFO),
        format="%(asctime)s %(name)s %(levelname)s %(message)s",
    )

    sock_path = Path(args.socket_path)
    # Clean stale socket
    if sock_path.exists():
        sock_path.unlink()
    sock_path.parent.mkdir(parents=True, exist_ok=True)

    app = _build_app(args.db_path, args.routes_file)

    # Graceful shutdown on SIGTERM
    def _handle_sigterm(*_: object) -> None:
        _logger.info("SIGTERM received, shutting down")
        raise SystemExit(0)

    signal.signal(signal.SIGTERM, _handle_sigterm)

    _logger.info("Listening on %s", sock_path)
    web.run_app(app, path=str(sock_path), print=lambda *_: None)


if __name__ == "__main__":
    main()
