# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Vault token broker — HTTP/WebSocket reverse proxy with secret injection.

This module has **zero terok imports**.  It is a self-contained security
component embedded by [`VaultProxy`][terok_sandbox.vault.daemon.token_broker.VaultProxy]
inside each per-container supervisor: an aiohttp app that listens on a
per-container Unix socket (or 127.0.0.1 TCP port), validates phantom
tokens against a SQLCipher database, injects real credentials from the
same database, and forwards requests to upstream API servers.

Task containers see only phantom API keys (worthless outside the broker).
Real secrets never enter the container filesystem or environment.

Route config (JSON, generated by terok-executor from the YAML registry)::

    {
        "anthropic": {
            "upstream": "https://api.anthropic.com",
            "auth_header": "Authorization",
            "auth_prefix": "Bearer ",
        }
    }
"""

from __future__ import annotations

import asyncio
import contextlib
import json
import logging
import socket
import time
from datetime import UTC, datetime
from pathlib import Path
from typing import TYPE_CHECKING, Any

if TYPE_CHECKING:
    from ..store.db import SSHKeyRecord

from aiohttp import (
    ClientResponse,
    ClientSession,
    ClientTimeout,
    ServerDisconnectedError,
    TCPConnector,
    WSMsgType,
    web,
)

from .audit import AuditWriter

_logger = logging.getLogger("terok-vault")

# Periodic OAuth refresh: the supervisor wakes every
# ``_REFRESH_INTERVAL`` seconds, walks the refreshable credentials in
# scope, and renews anything expiring within ``_REFRESH_BUFFER``.  The
# buffer is generous relative to the interval so a brief scheduler
# hiccup can't drop a still-valid token to a 401.
_REFRESH_INTERVAL = 300  # seconds between background refresh checks
_REFRESH_BUFFER = 600  # refresh tokens expiring within this many seconds

# Typed app keys (avoids NotAppKeyWarning on aiohttp >= 3.9).
# ``_RouteTable`` / ``_TokenDB`` AppKeys are declared after their class
# bodies further down the file because ``AppKey`` evaluates its second
# argument at runtime and can't accept a forward-reference string.
_KEY_CLIENT = web.AppKey("client_session", ClientSession)
_KEY_REFRESH_TASK: web.AppKey[asyncio.Task[None]] = web.AppKey("refresh_task", asyncio.Task)
_KEY_AUDIT = web.AppKey("audit", AuditWriter)

_IDEMPOTENT_METHODS = frozenset({"GET", "HEAD", "OPTIONS"})
_WEBSOCKET_MAX_MSG_SIZE = 16 * 1024 * 1024
_WEBSOCKET_INTERNAL_ERROR = 1011

#: Idle read timeout (seconds) for a proxied upstream response — the gap between
#: reads (for a stream, between chunks; for a unary response, the wait for the
#: whole body to land).  Set generously so the proxy is never stricter than the
#: agent it fronts: each client enforces its own (shorter) idle timeout and gives
#: up first, so this only bounds a silently-hung upstream the client isn't
#: watching.  The 10s connect timeout still detects dead-on-arrival upstreams.
_UPSTREAM_READ_TIMEOUT = 1200

#: Max proxied request body (bytes).  aiohttp's default is 1 MiB; codex's remote
#: compaction uploads the whole transcript and exceeded it (an observed 413), and
#: large contexts or base64 images can too.  The real limit belongs to the
#: upstream, not this proxy — this is just a generous bound that keeps a single
#: buffered body from being unbounded.
_MAX_REQUEST_BODY_SIZE = 128 * 1024 * 1024

# ---------------------------------------------------------------------------
# Route + credential loading (inlined, no terok imports)
# ---------------------------------------------------------------------------


class _RouteTable:
    """Provider routing table loaded from a JSON file."""

    def __init__(self, routes_path: str) -> None:
        with open(routes_path) as f:
            self._routes: dict[str, dict] = json.load(f)
        for name, cfg in self._routes.items():
            if "upstream" not in cfg:
                raise ValueError(f"Route '{name}' missing required 'upstream' field")
            path_upstreams = cfg.get("path_upstreams", {})
            if not isinstance(path_upstreams, dict):
                raise ValueError(f"Route '{name}' has invalid 'path_upstreams' field")
            for prefix, upstream in path_upstreams.items():
                if not isinstance(prefix, str) or not prefix.startswith("/"):
                    raise ValueError(
                        f"Route '{name}' path_upstreams key must start with '/': {prefix!r}"
                    )
                if not isinstance(upstream, str) or not upstream:
                    raise ValueError(
                        f"Route '{name}' path_upstreams entry for {prefix!r} is invalid"
                    )
            oauth_extra_headers = cfg.get("oauth_extra_headers", {})
            if not isinstance(oauth_extra_headers, dict):
                raise ValueError(f"Route '{name}' has invalid 'oauth_extra_headers' field")
            for header, value in oauth_extra_headers.items():
                if not isinstance(header, str) or not header:
                    raise ValueError(f"Route '{name}' oauth_extra_headers key is invalid")
                if not isinstance(value, str):
                    raise ValueError(
                        f"Route '{name}' oauth_extra_headers value for {header!r} is invalid"
                    )

    def get(self, provider: str) -> dict | None:
        """Return the route config for *provider*, or ``None``."""
        return self._routes.get(provider)


class _TokenDB:
    """Read-only sqlite3 accessor for phantom tokens, credentials, and SSH keys.

    Kept deliberately thin — only the SELECTs the vault daemon needs at
    request-handling time.  Writers go through
    [`terok_sandbox.vault.store.db.CredentialDB`][terok_sandbox.vault.store.db.CredentialDB].
    """

    def __init__(self, db_path: str, *, passphrase: str | None = None) -> None:
        """Open *db_path*; resolve the vault passphrase unless one is supplied."""
        # check_same_thread=False is safe: this is a read-only accessor and
        # aiohttp runs handlers in a single event loop thread.
        from ..store.encryption import open_sqlcipher

        if passphrase is None:
            from terok_sandbox.config import SandboxConfig

            from ..store.encryption import NoPassphraseError

            cfg = SandboxConfig()
            passphrase, source = cfg.resolve_passphrase_with_source()
            if passphrase is None:
                _logger.info("Vault passphrase: no tier resolved")
                raise NoPassphraseError(f"no SQLCipher passphrase available for {db_path}")
            _logger.info("Vault passphrase resolved via %s tier", source)
        self._conn = open_sqlcipher(db_path, passphrase, check_same_thread=False)
        self._conn.execute("PRAGMA journal_mode=WAL")
        # Bootstrap + migrate schema here too so the vault daemon can open
        # an empty DB on a fresh install (no CLI write has touched the file
        # yet) and a post-upgrade DB (v0 columns) without crashing on the
        # first query.  Both helpers are idempotent.
        from ..store.db import ensure_credentials_schema, migrate_credential_db_schema

        ensure_credentials_schema(self._conn)
        migrate_credential_db_schema(self._conn)

    def lookup_token(self, token: str) -> dict | None:
        """Return ``{scope, subject, credential_set, provider}`` or ``None``."""
        row = self._conn.execute(
            "SELECT scope, subject, credential_set, provider FROM proxy_tokens WHERE token = ?",
            (token,),
        ).fetchone()
        if row is None:
            return None
        return {
            "scope": row[0],
            "subject": row[1],
            "credential_set": row[2],
            "provider": row[3],
        }

    def load_credential(self, credential_set: str, provider: str) -> dict | None:
        """Return parsed credential data dict, or ``None``."""
        row = self._conn.execute(
            "SELECT data FROM credentials WHERE credential_set = ? AND provider = ?",
            (credential_set, provider),
        ).fetchone()
        return json.loads(row[0]) if row else None

    def load_ssh_keys_for_scope(self, scope: str) -> list[SSHKeyRecord]:
        """Return full SSH key records (including raw bytes) assigned to *scope*."""
        from ..store.db import SSHKeyRecord

        rows = self._conn.execute(
            "SELECT k.id, k.key_type, k.private_der, k.public_blob,"
            " k.comment, k.fingerprint"
            " FROM ssh_keys k"
            " JOIN ssh_key_assignments a ON a.key_id = k.id"
            " WHERE a.scope = ?"
            " ORDER BY a.assigned_at",
            (scope,),
        ).fetchall()
        return [SSHKeyRecord(*r) for r in rows]

    def list_refreshable(self) -> list[tuple[str, str, dict]]:
        """Return ``(credential_set, provider, data)`` for OAuth creds with a refresh token."""
        rows = self._conn.execute(
            "SELECT credential_set, provider, data FROM credentials"
        ).fetchall()
        result: list[tuple[str, str, dict]] = []
        for cs, prov, raw in rows:
            data = json.loads(raw)
            if data.get("type") == "oauth" and data.get("refresh_token"):
                result.append((cs, prov, data))
        return result

    def update_credential(self, credential_set: str, provider: str, data: dict) -> None:
        """Update the data blob for an existing credential."""
        self._conn.execute(
            "UPDATE credentials SET data = ? WHERE credential_set = ? AND provider = ?",
            (json.dumps(data), credential_set, provider),
        )
        self._conn.commit()

    def close(self) -> None:
        """Close the database connection."""
        self._conn.close()

    def __del__(self) -> None:
        """Best-effort close on garbage collection."""
        try:
            self._conn.close()
        except Exception:  # noqa: BLE001  # nosec B110 — best-effort __del__ close on GC
            pass


# Typed AppKeys for ``_RouteTable`` / ``_TokenDB`` are declared down here
# (not next to ``_KEY_CLIENT`` further up) because ``web.AppKey`` evaluates
# its second argument at runtime and would forward-reference fail if these
# stood above the class bodies.
_KEY_ROUTES = web.AppKey("routes", _RouteTable)
_KEY_TOKEN_DB = web.AppKey("token_db", _TokenDB)
#: Directory for the cross-supervisor refresh ``flock`` files.  Seeded
#: from the ambient runtime dir in ``_build_app`` (standalone callers)
#: and overridden by ``VaultProxy.start`` with the lock dir resolved
#: once from the injected ``runtime_dir`` — the only reliable anchor in
#: crun's rootless userns, where ``getuid()`` and ``XDG_RUNTIME_DIR``
#: misroute the path.
_KEY_LOCK_DIR = web.AppKey("refresh_lock_dir", Path)


# ---------------------------------------------------------------------------
# Auth extraction helpers
# ---------------------------------------------------------------------------

_AUTH_HEADERS = ("authorization", "x-api-key", "private-token")

# Hop-by-hop headers per RFC 7230 §6.1 — a reverse proxy MUST NOT forward
# these.  ``Connection`` may name additional hop-by-hop headers; those are
# stripped dynamically per request.
_HOP_BY_HOP_HEADERS = frozenset(
    {
        "connection",
        "keep-alive",
        "proxy-authenticate",
        "proxy-authorization",
        "te",
        "trailer",
        "transfer-encoding",
        "upgrade",
    }
)


def _extract_phantom_token(request: web.Request) -> str | None:
    """Extract a phantom token from Authorization or X-Api-Key headers."""
    for header in _AUTH_HEADERS:
        value = request.headers.get(header)
        if not value:
            continue
        # Strip "Bearer ", "token ", etc. prefixes
        if " " in value:
            return value.split(None, 1)[1]
        return value
    return None


def _static_oauth_token_info(token: str) -> dict | None:
    """Return synthetic token metadata for shared OAuth marker tokens."""
    from . import CODEX_SHARED_OAUTH_MARKER, PHANTOM_CREDENTIALS_MARKER

    # Keyed by the *provider* each shared-OAuth marker authenticates to — the
    # broker resolves routes off the bearer token, so these must match the
    # re-keyed routes.json/credentials vocabulary (claude→anthropic,
    # codex→openai), not the agent names the markers are named after.
    static_markers = {
        PHANTOM_CREDENTIALS_MARKER: "anthropic",
        CODEX_SHARED_OAUTH_MARKER: "openai",
    }
    provider = static_markers.get(token)
    if provider is None:
        return None
    _logger.debug("Accepting static phantom marker for %s OAuth", provider)
    return {
        "scope": "__static__",
        "subject": "__static__",
        "credential_set": "default",
        "provider": provider,
    }


def _path_matches_prefix(path: str, prefix: str) -> bool:
    """Return whether *path* matches the configured path-prefix override."""
    normalized = prefix if prefix.startswith("/") else f"/{prefix}"
    if path == normalized:
        return True
    if normalized.endswith("/"):
        return path.startswith(normalized)
    return path.startswith(f"{normalized}/")


def _select_upstream(route: dict, path: str) -> str:
    """Pick the upstream base URL for *path* using longest-prefix matching."""
    selected = route["upstream"]
    best_len = -1
    for prefix, upstream in (route.get("path_upstreams") or {}).items():
        if _path_matches_prefix(path, prefix) and len(prefix) > best_len:
            selected = upstream
            best_len = len(prefix)
    return selected


def _build_upstream_url(upstream_base: str, path: str, query_string: str) -> str:
    """Join an upstream base URL with the inbound request path and query."""
    from urllib.parse import urlparse

    parsed = urlparse(upstream_base)
    base_path = parsed.path.rstrip("/")
    upstream_path = f"{base_path}{path}" if base_path else path
    if not upstream_path.startswith("/"):
        upstream_path = f"/{upstream_path}"
    upstream_url = f"{parsed.scheme}://{parsed.netloc}{upstream_path}"
    if query_string:
        upstream_url += f"?{query_string}"
    return upstream_url


def _requested_websocket_protocols(request: web.Request) -> list[str]:
    """Return websocket subprotocols requested by the client, in order."""
    protocols: list[str] = []
    for value in request.headers.getall("Sec-WebSocket-Protocol", []):
        protocols.extend(part.strip() for part in value.split(",") if part.strip())
    return protocols


async def _proxy_websocket(
    request: web.Request,
    *,
    session: ClientSession,
    upstream_url: str,
    headers: dict[str, str],
    provider: str,
) -> web.StreamResponse:
    """Bridge a client websocket to the upstream websocket with auth injection."""
    protocols = _requested_websocket_protocols(request)
    client_ws: web.WebSocketResponse | None = None
    try:
        async with session.ws_connect(
            upstream_url,
            headers=headers,
            protocols=protocols,
            autoping=False,
            autoclose=False,
            heartbeat=30,
            max_msg_size=_WEBSOCKET_MAX_MSG_SIZE,
        ) as upstream_ws:
            response_protocols = [upstream_ws.protocol] if upstream_ws.protocol else []
            client_ws = web.WebSocketResponse(
                protocols=response_protocols,
                autoping=False,
                autoclose=False,
                max_msg_size=_WEBSOCKET_MAX_MSG_SIZE,
            )
            await client_ws.prepare(request)

            async def _client_to_upstream() -> None:
                async for msg in client_ws:
                    if msg.type is WSMsgType.TEXT:
                        await upstream_ws.send_str(msg.data)
                    elif msg.type is WSMsgType.BINARY:
                        await upstream_ws.send_bytes(msg.data)
                    elif msg.type is WSMsgType.PING:
                        await upstream_ws.ping(msg.data)
                    elif msg.type is WSMsgType.PONG:
                        await upstream_ws.pong(msg.data)
                    else:
                        await upstream_ws.close()
                        return

            async def _upstream_to_client() -> None:
                async for msg in upstream_ws:
                    if msg.type is WSMsgType.TEXT:
                        await client_ws.send_str(msg.data)
                    elif msg.type is WSMsgType.BINARY:
                        await client_ws.send_bytes(msg.data)
                    elif msg.type is WSMsgType.PING:
                        await client_ws.ping(msg.data)
                    elif msg.type is WSMsgType.PONG:
                        await client_ws.pong(msg.data)
                    else:
                        await client_ws.close(code=upstream_ws.close_code or 1000)
                        return

            tasks = {
                asyncio.create_task(_client_to_upstream()),
                asyncio.create_task(_upstream_to_client()),
            }
            done, pending = await asyncio.wait(tasks, return_when=asyncio.FIRST_COMPLETED)
            for task in pending:
                task.cancel()
            await asyncio.gather(*pending, return_exceptions=True)
            for task in done:
                task.result()
            if not client_ws.closed:
                await client_ws.close(code=upstream_ws.close_code or 1000)
            return client_ws
    except Exception as exc:
        _logger.error("Upstream websocket to %s failed: %s", provider, exc)
        if client_ws is not None and client_ws.prepared:
            if not client_ws.closed:
                await client_ws.close(code=_WEBSOCKET_INTERNAL_ERROR)
            return client_ws
        return web.Response(status=502, text="Upstream websocket failed")


# ---------------------------------------------------------------------------
# Request handler
# ---------------------------------------------------------------------------


async def _audit_request(
    request: web.Request,
    token_info: dict | None,
    status: int,
    outcome: str,
    started_at: float,
) -> None:
    """Append one credential-audit line for *request*.  Soft-fails on every error.

    ``token_info`` may be ``None`` for early-return paths (missing or
    invalid phantom) — the caller-supplied label fields are then empty.
    The audit writer's own ``write`` is the soft-fail boundary; this
    helper just shapes the entry.  WebSocket sessions are deliberately
    not audited in v1: the proxy hands off to a separate streaming loop
    whose lifetime doesn't fit a single request line.
    """
    audit = request.app.get(_KEY_AUDIT)
    if audit is None:
        return
    info = token_info or {}
    entry = {
        "ts": datetime.now(UTC).isoformat(timespec="seconds"),
        "scope": info.get("scope", ""),
        "subject": info.get("subject", ""),
        "credential_set": info.get("credential_set", ""),
        "provider": info.get("provider", ""),
        "method": request.method,
        "path": request.path,
        "status": status,
        "outcome": outcome,
        "duration_ms": int((time.monotonic() - started_at) * 1000),
    }
    await audit.write(entry)


# ---------------------------------------------------------------------------
# Response relay and redirect resolution
# ---------------------------------------------------------------------------

# Response headers relayed verbatim to the client.  The body is re-streamed,
# so aiohttp regenerates the framing headers (content-length, content-encoding);
# copying the upstream's would contradict the bytes actually sent.
_FORWARDED_RESPONSE_HEADERS = ("content-type", "transfer-encoding", "cache-control")

# A few provider endpoints (GitHub Actions logs/artifacts, release assets, repo
# tarballs) answer with a 3xx to a self-authenticating storage URL on a *different*
# host.  The container's HTTP client is pinned to this broker's socket, so it can
# neither reach that host nor follow the hop — and the broker routes by
# token-provider, so a replayed storage path would be rewritten back onto the
# provider's API host.  The broker therefore resolves such redirects itself.
_REDIRECT_STATUSES = frozenset({301, 302, 303, 307, 308})


def _is_followable_redirect(status: int, method: str) -> bool:
    """Whether a redirect response should be resolved inside the broker.

    Only idempotent methods qualify: replaying a write body across a redirect
    could duplicate a non-idempotent effect, so those redirects are relayed back
    to the client untouched instead of being followed here.
    """
    return status in _REDIRECT_STATUSES and method.upper() in _IDEMPOTENT_METHODS


async def _stream_upstream(
    request: web.Request,
    upstream: ClientResponse,
    *,
    token_info: dict,
    started_at: float,
) -> web.StreamResponse:
    """Relay an upstream response's status, selected headers, and streamed body."""
    resp = web.StreamResponse(status=upstream.status)
    for hdr in _FORWARDED_RESPONSE_HEADERS:
        if value := upstream.headers.get(hdr):
            resp.headers[hdr] = value
    await resp.prepare(request)
    async for chunk in upstream.content.iter_any():
        await resp.write(chunk)
    await resp.write_eof()
    await _audit_request(request, token_info, upstream.status, "ok", started_at)
    return resp


async def _resolve_redirect(
    request: web.Request,
    session: ClientSession,
    location: str,
    base_url: str,
    *,
    token_info: dict,
    started_at: float,
) -> web.StreamResponse:
    """Fetch a redirect target with the injected credential dropped, then stream it.

    The ``Location`` points at a self-authenticating URL on a third-party host;
    withholding the real provider token keeps it from leaking off the provider's
    own origin — the same rule curl and browsers apply on a cross-origin redirect.
    aiohttp chases any further hops, bounded by its default redirect cap.
    """
    from urllib.parse import urljoin

    target = urljoin(base_url, location)
    follow_headers = {
        name: request.headers[name] for name in ("accept", "user-agent") if name in request.headers
    }
    async with session.get(
        target,
        headers=follow_headers,
        allow_redirects=True,
        timeout=ClientTimeout(connect=10, sock_read=_UPSTREAM_READ_TIMEOUT),
    ) as final:
        return await _stream_upstream(request, final, token_info=token_info, started_at=started_at)


async def _handle_request(request: web.Request) -> web.StreamResponse:
    """Authenticate, route by token, inject credentials, and forward to upstream."""
    started_at = time.monotonic()
    routes: _RouteTable = request.app[_KEY_ROUTES]
    token_db: _TokenDB = request.app[_KEY_TOKEN_DB]

    # 1. Validate phantom token
    phantom = _extract_phantom_token(request)
    if not phantom:
        _logger.warning("%s %s -> 401 Missing authentication", request.method, request.path)
        await _audit_request(request, None, 401, "missing_token", started_at)
        return web.Response(status=401, text="Missing authentication")

    token_info = token_db.lookup_token(phantom)
    if token_info is None:
        if static_info := _static_oauth_token_info(phantom):
            token_info = static_info
        else:
            _logger.warning("%s %s -> 401 Invalid token", request.method, request.path)
            await _audit_request(request, None, 401, "invalid_token", started_at)
            return web.Response(status=401, text="Invalid token")

    # 2. Route by token's provider
    provider = token_info["provider"]
    route = routes.get(provider)
    if route is None:
        _logger.warning(
            "%s %s -> 404 No route for provider: %s", request.method, request.path, provider
        )
        await _audit_request(request, token_info, 404, "no_route", started_at)
        return web.Response(status=404, text=f"No route for provider: {provider}")
    rest = request.path

    # 3. Load real credential
    cred = token_db.load_credential(token_info["credential_set"], provider)
    if cred is None:
        _logger.warning(
            "No credential for provider %r in set %r", provider, token_info["credential_set"]
        )
        await _audit_request(request, token_info, 502, "credential_missing", started_at)
        return web.Response(status=502, text="Credential not configured for this provider")

    # Determine the real auth value and header based on credential type.
    # OAuth tokens use "Authorization: Bearer <token>"; API keys use the
    # route-configured header (e.g. "x-api-key: <key>").
    # Legacy rows without "type" are detected by the presence of "access_token".
    cred_type = cred.get("type", "")
    is_oauth = cred_type == "oauth" or (not cred_type and "access_token" in cred)
    if is_oauth:
        real_token = cred.get("access_token")
        if not real_token:
            _logger.error("Credential for %r is OAuth but missing access_token", provider)
            await _audit_request(request, token_info, 502, "credential_misconfigured", started_at)
            return web.Response(status=502, text="Credential misconfigured")
        auth_header = "Authorization"
        auth_prefix = "Bearer "
    else:
        real_token = cred.get("token") or cred.get("key")
        if not real_token:
            _logger.error("Credential for %r has no usable token field", provider)
            await _audit_request(request, token_info, 502, "credential_misconfigured", started_at)
            return web.Response(status=502, text="Credential misconfigured")
        auth_header = route.get("auth_header", "Authorization")
        auth_prefix = route.get("auth_prefix", "Bearer ")
        # "dynamic" means auto-detect — for API keys, use x-api-key
        if auth_header == "dynamic":
            auth_header = "x-api-key"
            auth_prefix = ""

    # 4. Build upstream request — strip phantom auth, inject real auth
    upstream_base = _select_upstream(route, rest)
    upstream_url = _build_upstream_url(upstream_base, rest, request.query_string)

    # Strip auth, host, and RFC 7230 hop-by-hop headers (plus any names the
    # client listed in its Connection header) before forwarding upstream.
    dropped = {t.strip().lower() for t in request.headers.get("Connection", "").split(",")}
    dropped |= _HOP_BY_HOP_HEADERS
    dropped |= set(_AUTH_HEADERS)
    dropped.add("host")
    dropped.discard("")
    headers = {k: v for k, v in request.headers.items() if k.lower() not in dropped}
    headers[auth_header] = f"{auth_prefix}{real_token}"
    if is_oauth:
        for header, value in (route.get("oauth_extra_headers") or {}).items():
            existing_values = [
                part.strip() for part in headers.get(header, "").split(",") if part.strip()
            ]
            if value not in existing_values:
                headers[header] = ",".join([*existing_values, value])

    session: ClientSession = request.app[_KEY_CLIENT]
    if request.headers.get("Upgrade", "").lower() == "websocket":
        # WebSocket sessions deliberately bypass the audit log in v1 — the
        # streaming loop has no single status / duration we can record
        # inside one JSONL line.  Per-frame audit is unbounded; an open /
        # close pair is the natural follow-up.
        return await _proxy_websocket(
            request,
            session=session,
            upstream_url=upstream_url,
            headers=headers,
            provider=provider,
        )

    # 5. Forward and stream response
    # Read the body once (streaming body can only be consumed once).
    body = await request.read() if request.can_read_body else None
    # Only retry idempotent methods (or those with an Idempotency-Key header) to
    # avoid replaying non-idempotent writes on stale-connection recovery.
    can_retry = (
        request.method.upper() in _IDEMPOTENT_METHODS or "idempotency-key" in request.headers
    )
    for attempt in range(2 if can_retry else 1):
        # Track whether __aenter__ succeeded so we never retry after resp.prepare().
        connection_established = False
        try:
            async with session.request(
                request.method,
                upstream_url,
                headers=headers,
                data=body,
                allow_redirects=False,
                timeout=ClientTimeout(connect=10, sock_read=_UPSTREAM_READ_TIMEOUT),
            ) as upstream:
                connection_established = True
                location = upstream.headers.get("location")
                if location and _is_followable_redirect(upstream.status, request.method):
                    return await _resolve_redirect(
                        request,
                        session,
                        location,
                        str(upstream.url),
                        token_info=token_info,
                        started_at=started_at,
                    )
                return await _stream_upstream(
                    request, upstream, token_info=token_info, started_at=started_at
                )
        except ServerDisconnectedError:
            if not connection_established and attempt == 0 and can_retry:
                _logger.debug("Upstream %s disconnected on pooled conn, retrying", provider)
                continue
            _logger.error("Upstream %s disconnected on fresh connection", provider)
            await _audit_request(request, token_info, 502, "upstream_disconnected", started_at)
            return web.Response(status=502, text="Upstream disconnected")
        except Exception as exc:
            _logger.error("Upstream request to %s failed: %s", provider, exc)
            await _audit_request(request, token_info, 502, "upstream_error", started_at)
            return web.Response(status=502, text="Upstream request failed")
    await _audit_request(request, token_info, 502, "upstream_disconnected", started_at)
    return web.Response(status=502, text="Upstream disconnected")  # unreachable


# ---------------------------------------------------------------------------
# Background OAuth token refresh
# ---------------------------------------------------------------------------


async def _do_oauth_refresh(
    session: ClientSession, provider: str, oauth_cfg: dict, cred: dict
) -> dict:
    """Call the provider's token endpoint and return an updated credential dict.

    Raises on network or HTTP errors so callers can log and continue.
    """
    payload = {
        "grant_type": "refresh_token",
        "refresh_token": cred["refresh_token"],
        "client_id": oauth_cfg["client_id"],
    }
    if "scope" in oauth_cfg:
        payload["scope"] = oauth_cfg["scope"]
    if "client_secret" in oauth_cfg:
        payload["client_secret"] = oauth_cfg["client_secret"]

    # NOTE: RFC 6749 specifies application/x-www-form-urlencoded for token
    # requests, but both Anthropic's and Codex/OpenAI's current refresh
    # endpoints accept JSON payloads.  If a future provider needs form
    # encoding, add a per-provider `token_content_type` YAML field then.
    async with session.post(
        oauth_cfg["token_url"],
        json=payload,
        timeout=ClientTimeout(total=15),
    ) as resp:
        if resp.status != 200:
            # Do NOT include the response body — token endpoints sometimes
            # echo the request payload (including the refresh_token and
            # client_secret) in error responses, and this exception is
            # logged by ``_refresh_all`` via ``_logger.exception``.
            raise RuntimeError(f"Token refresh failed (status={resp.status})")
        data = await resp.json()

    return {
        **cred,
        "access_token": data["access_token"],
        "refresh_token": data.get("refresh_token", cred["refresh_token"]),
        "expires_at": time.time() + data.get("expires_in", 28800),
    }


def _ambient_lock_dir() -> Path:
    """Refresh-lock dir derived from the ambient runtime env.

    Used as the default for standalone callers (``_build_app`` without a
    surrounding [`VaultProxy`][terok_sandbox.vault.daemon.token_broker.VaultProxy]).
    The supervisor path injects an explicit ``runtime_dir`` instead and
    pins the resolved dir on the app under ``_KEY_LOCK_DIR``.
    """
    import os as _os

    runtime = _os.environ.get("XDG_RUNTIME_DIR") or f"/run/user/{_os.getuid()}"
    return Path(runtime) / "terok" / "vault" / "locks"


async def _refresh_all(app: web.Application) -> None:
    """Check all OAuth credentials and refresh any that are expired or expiring soon.

    Cross-supervisor coordination: each per-supervisor refresh task
    contends a non-blocking ``flock`` on
    ``refresh-<credential_set>-<provider>.lock``.  A contended lock
    means another supervisor is already refreshing the same row; this
    one skips and picks up the freshly-written state on its next read.
    """
    token_db: _TokenDB = app[_KEY_TOKEN_DB]
    routes: _RouteTable = app[_KEY_ROUTES]
    session: ClientSession = app[_KEY_CLIENT]
    # The lock dir is resolved once at app-build / supervisor-start time
    # and stashed on the app — never recomputed from ambient env per
    # tick, which would misroute the path under crun's rootless userns.
    lock_dir = app[_KEY_LOCK_DIR]

    for cs, provider, cred in token_db.list_refreshable():
        route = routes.get(provider)
        if not route or "oauth_refresh" not in route:
            continue
        expires_at = cred.get("expires_at")
        if expires_at and time.time() < expires_at - _REFRESH_BUFFER:
            continue  # still valid

        fd = acquire_refresh_lock(lock_dir, cs, provider)
        if fd is None:
            _logger.debug(
                "Another supervisor is refreshing %s/%s; skipping this tick", cs, provider
            )
            continue
        try:
            # Re-read the row inside the lock — the other supervisor may
            # have refreshed it while we were waiting on dependencies.
            fresh = token_db.load_credential(cs, provider) or cred
            fresh_expires = fresh.get("expires_at")
            if fresh_expires and time.time() < fresh_expires - _REFRESH_BUFFER:
                continue  # peer already refreshed

            _logger.info("Refreshing OAuth token for %s (credential_set=%s)", provider, cs)
            try:
                new_cred = await _do_oauth_refresh(session, provider, route["oauth_refresh"], fresh)
                token_db.update_credential(cs, provider, new_cred)
                _logger.info(
                    "Refreshed OAuth token for %s (expires in %ds)",
                    provider,
                    int(new_cred["expires_at"] - time.time()),
                )
            except Exception:
                _logger.exception("Failed to refresh OAuth token for %s", provider)
        finally:
            release_refresh_lock(fd)


async def _refresh_loop(app: web.Application) -> None:
    """Run an immediate refresh check, then repeat every ``_REFRESH_INTERVAL`` seconds."""
    while True:
        try:
            await _refresh_all(app)
        except asyncio.CancelledError:
            raise
        except Exception:
            _logger.exception("OAuth refresh cycle failed")
        await asyncio.sleep(_REFRESH_INTERVAL)


# ---------------------------------------------------------------------------
# Application lifecycle
# ---------------------------------------------------------------------------


async def _on_startup(app: web.Application) -> None:
    """Create the shared HTTP client session and start background refresh."""
    # keepalive_timeout=30 ensures we retire connections before upstream servers
    # close them (~60-90s typical for Anthropic/OpenAI), preventing stale-pool 502s.
    connector = TCPConnector(enable_cleanup_closed=True, keepalive_timeout=30)
    app[_KEY_CLIENT] = ClientSession(connector=connector)
    app[_KEY_REFRESH_TASK] = asyncio.create_task(_refresh_loop(app))


async def _on_cleanup(app: web.Application) -> None:
    """Close client session, cancel background tasks, and close token DB."""
    task = app.get(_KEY_REFRESH_TASK)
    if task is not None:
        task.cancel()
        # contextlib.suppress sidesteps Sonar S7497 — the CancelledError
        # here is the *child*'s acknowledgement of our explicit cancel(),
        # not the cleanup task's own cancellation, so it must not propagate.
        with contextlib.suppress(asyncio.CancelledError):
            await task
    await app[_KEY_CLIENT].close()
    app[_KEY_TOKEN_DB].close()
    audit = app.get(_KEY_AUDIT)
    if audit is not None:
        await audit.close()


async def _handle_health(_request: web.Request) -> web.Response:
    """Return 200 — unauthenticated readiness probe for lifecycle management."""
    return web.json_response({"status": "ok"})


def _build_app(db_path: str, routes_path: str, audit_path: Path | None = None) -> web.Application:
    """Construct the aiohttp application.

    *audit_path* — when supplied, every credential-bearing request lands
    one JSONL line at this path.  ``None`` disables auditing (used by
    smoke tests that don't care about the side-channel); production
    callers point at [`credential_audit_log_path`][terok_sandbox.vault.daemon.audit.credential_audit_log_path].
    """
    app = web.Application(client_max_size=_MAX_REQUEST_BODY_SIZE)
    app[_KEY_ROUTES] = _RouteTable(routes_path)
    app[_KEY_TOKEN_DB] = _TokenDB(db_path)
    # Default refresh-lock dir for standalone callers; VaultProxy.start
    # overrides this with the dir resolved from its injected runtime_dir.
    app[_KEY_LOCK_DIR] = _ambient_lock_dir()
    if audit_path is not None:
        app[_KEY_AUDIT] = AuditWriter(audit_path)
    app.on_startup.append(_on_startup)
    app.on_cleanup.append(_on_cleanup)
    from . import HEALTH_PATH

    app.router.add_get(HEALTH_PATH, _handle_health)
    app.router.add_route("*", "/{tail:.*}", _handle_request)
    return app


# ---------------------------------------------------------------------------
# VaultProxy — embeddable class for the per-container supervisor.
# ---------------------------------------------------------------------------


from dataclasses import dataclass  # noqa: E402 — keep close to use sites below


@dataclass(frozen=True)
class UnixBind:
    """Unix-domain bind for the vault HTTP proxy.

    Used by the supervisor in socket mode.  The proxy binds the socket
    with mode ``0600`` so only the same-UID rootless container peers
    via the bind-mount.
    """

    socket_path: Path


@dataclass(frozen=True)
class TcpBind:
    """TCP bind for the vault HTTP proxy.

    Used by the supervisor in TCP mode (krun / SELinux-restricted
    distros).  Always pins to ``127.0.0.1``; the shield egress
    firewall would refuse loopback traffic on any other interface
    anyway.
    """

    host: str
    port: int


class VaultProxy:
    """Embeddable aiohttp vault — one per container, owned by the supervisor.

    Each per-container supervisor builds a fresh
    [`VaultProxy`][terok_sandbox.vault.daemon.token_broker.VaultProxy]
    bound to a per-container socket (or TCP port); it serves only its
    own container and lives only as long as that container itself.

    Two transport flavours, picked by *bind* at construction:

    - [`UnixBind`][terok_sandbox.vault.daemon.token_broker.UnixBind] —
      a single mode-0600 Unix socket the rootless container reaches via
      bind-mount.  The supervisor places the socket under
      ``$XDG_RUNTIME_DIR/terok/vault/<container_id>.sock``.
    - [`TcpBind`][terok_sandbox.vault.daemon.token_broker.TcpBind] —
      ``127.0.0.1:<port>`` for the krun / SELinux-restricted path; the
      shield's loopback allowlist covers the container side.

    The OAuth refresh task runs every ``_REFRESH_INTERVAL``
    seconds inside the same loop.  Cross-supervisor coordination uses a
    non-blocking ``flock`` on
    ``$XDG_RUNTIME_DIR/terok/vault/locks/refresh-<credential_set>-<provider>.lock``:
    a contended lock means another supervisor is already refreshing the
    same row, so we skip and pick up the fresh value on the next read.
    """

    def __init__(
        self,
        *,
        db_path: Path | str,
        scope_id: str | None,
        bind: UnixBind | TcpBind,
        routes_path: Path | str | None = None,
        audit_path: Path | None = None,
        runtime_dir: Path | None = None,
    ) -> None:
        """Wire the proxy to the credential DB and a transport.

        *scope_id* is informational at present — the broker authorises
        per-token via ``_TokenDB.lookup_token``,
        not by scope.  Reserved for future per-supervisor scope-filtering
        (e.g. refusing tokens outside the supervisor's container scope).

        *routes_path* defaults to ``$XDG_CONFIG_HOME/terok/vault/routes.json``
        when omitted — the canonical location ``terok-executor`` writes
        the route table to.

        *runtime_dir* — explicit runtime root for the cross-supervisor
        refresh ``flock`` files.  Required when the proxy runs in
        crun's rootless userns (``getuid()`` reports ``0`` there but
        the actual host runtime dir is under the operator's uid); if
        omitted, falls back to ``$XDG_RUNTIME_DIR`` / ``/run/user/<uid>``.
        """
        from terok_sandbox.config import SandboxConfig

        cfg = SandboxConfig()
        self._db_path = str(db_path)
        self._scope_id = scope_id
        self._bind = bind
        self._routes_path = str(routes_path) if routes_path else str(cfg.routes_path)
        self._audit_path = audit_path
        self._runtime_dir = runtime_dir
        self._app: web.Application | None = None
        self._runner: Any | None = None
        self._site: Any | None = None
        self._refresh_lock_dir: Path | None = None

    @property
    def bind(self) -> UnixBind | TcpBind:
        """Return the transport binding the proxy was constructed with."""
        return self._bind

    @property
    def scope_id(self) -> str | None:
        """Return the scope the proxy was constructed with (informational)."""
        return self._scope_id

    async def start(self) -> None:
        """Build the aiohttp app and bring the listener up.

        Initial-pass refresh runs at startup (same shape as
        ``_refresh_loop``)
        so the first request never blocks on a slow token-endpoint
        round-trip — the periodic task continues from there.
        """
        from aiohttp.web_runner import AppRunner, SockSite, TCPSite

        self._app = _build_app(self._db_path, self._routes_path, audit_path=self._audit_path)
        self._refresh_lock_dir = self._compute_refresh_lock_dir()
        # The refresh loop reads the lock dir off the app, so pin the
        # one resolved here (from the injected runtime_dir) over the
        # ambient-env default _build_app seeded.
        self._app[_KEY_LOCK_DIR] = self._refresh_lock_dir

        self._runner = AppRunner(self._app, access_log=_logger)
        await self._runner.setup()

        if isinstance(self._bind, UnixBind):
            sock = self._bind_unix_socket(self._bind.socket_path)
            self._site = SockSite(self._runner, sock)
        else:
            self._site = TCPSite(self._runner, self._bind.host, self._bind.port)
        await self._site.start()
        _logger.info("VaultProxy started on %s", self._describe_bind())

    async def stop(self) -> None:
        """Tear down the listener and free the aiohttp resources.

        Idempotent — a stop call on a never-started proxy is a no-op.
        """
        if self._runner is not None:
            await self._runner.cleanup()
            self._runner = None
            self._site = None
            self._app = None

    def _describe_bind(self) -> str:
        """Return a human-readable description of the active bind."""
        if isinstance(self._bind, UnixBind):
            return f"unix:{self._bind.socket_path}"
        return f"tcp://{self._bind.host}:{self._bind.port}"

    def _bind_unix_socket(self, path: Path) -> socket.socket:
        """Bind a mode-0600 ``AF_UNIX`` socket at *path*, with SELinux labelling.

        Hardened sequence: a stale-but-live check rejects collisions,
        a stale-and-dead socket is unlinked, the bind happens inside
        the SELinux context manager so the ``terok_socket_t`` label is
        process-scoped, and a post-bind ``harden_socket`` re-confirms
        the inode permissions.
        """
        import socket as _socket
        import stat as _stat

        from terok_sandbox._util._net import harden_socket
        from terok_sandbox._util._selinux import socket_selinux_context

        try:
            mode = path.lstat().st_mode
        except FileNotFoundError:
            pass
        else:
            if not _stat.S_ISSOCK(mode):
                raise RuntimeError(f"Refusing to remove non-socket path: {path}")
            probe = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
            try:
                if probe.connect_ex(str(path)) == 0:
                    raise RuntimeError(f"Socket path already in use: {path}")
            finally:
                probe.close()
            path.unlink()
        path.parent.mkdir(parents=True, exist_ok=True)
        with socket_selinux_context():
            sock = _socket.socket(_socket.AF_UNIX, _socket.SOCK_STREAM)
            try:
                sock.bind(str(path))
                sock.listen(128)
            except Exception:
                sock.close()
                raise
        harden_socket(path)
        return sock

    def _compute_refresh_lock_dir(self) -> Path:
        """Pick the directory where cross-supervisor refresh ``flock`` files live.

        Uses the explicit ``runtime_dir`` passed at construction time
        when available — that's the only reliable anchor when the
        proxy runs in crun's rootless userns, where ``getuid()`` lies
        and ``XDG_RUNTIME_DIR`` may resolve to ``/run/user/0``.  Falls
        back to the ambient runtime dir for standalone callers.
        Created on demand inside ``_acquire_refresh_lock`` so a
        soft-fail mkdir doesn't crash the listener bring-up.
        """
        if self._runtime_dir is not None:
            return self._runtime_dir / "terok" / "vault" / "locks"
        return _ambient_lock_dir()


# ---------------------------------------------------------------------------
# Cross-supervisor refresh-coordination flock helper.
# ---------------------------------------------------------------------------


def _safe_lock_component(value: str) -> str:
    """Reduce *value* to a single filesystem-safe path component.

    ``credential_set`` / ``provider`` originate from the credentials DB;
    a value carrying ``/`` or ``..`` would let the composed lock path
    escape ``lock_dir``.  Map every char outside ``[A-Za-z0-9._-]`` to
    ``_`` and append a short digest of the original so two distinct
    inputs can't sanitise to the same lock file.  Deterministic: the
    same input always yields the same component, which the
    cross-supervisor ``flock`` contention relies on.
    """
    import hashlib

    cleaned = "".join(ch if ch.isalnum() or ch in "._-" else "_" for ch in value)
    digest = hashlib.sha256(value.encode("utf-8")).hexdigest()[:12]
    return f"{cleaned}-{digest}"


def acquire_refresh_lock(lock_dir: Path, credential_set: str, provider: str) -> int | None:
    """Try to acquire an exclusive ``flock`` on the per-credential refresh file.

    Returns the held file-descriptor on success, ``None`` when another
    supervisor is already refreshing the same row (the lock is
    non-blocking, ``LOCK_NB``).  Callers ``os.close`` the fd to release.
    Soft-fails to ``None`` on any I/O error — the periodic task will
    pick the credential up again on the next tick.

    The lock file lives under
    ``$XDG_RUNTIME_DIR/terok/vault/locks/refresh-<credential_set>-<provider>.lock``;
    the directory is created with mode 0700 on demand.  The
    ``credential_set`` / ``provider`` components are sanitised (see
    ``_safe_lock_component``) so the lock file always stays inside
    *lock_dir*.
    """
    import fcntl
    import os as _os

    try:
        lock_dir.mkdir(parents=True, exist_ok=True)
        _os.chmod(lock_dir, 0o700)
    except OSError as exc:
        _logger.debug("refresh lock dir setup failed: %s", exc)
        return None
    safe_cs = _safe_lock_component(credential_set)
    safe_provider = _safe_lock_component(provider)
    lock_path = lock_dir / f"refresh-{safe_cs}-{safe_provider}.lock"
    try:
        fd = _os.open(lock_path, _os.O_RDWR | _os.O_CREAT | _os.O_CLOEXEC, 0o600)
    except OSError as exc:
        _logger.debug("refresh lock open failed: %s", exc)
        return None
    try:
        fcntl.flock(fd, fcntl.LOCK_EX | fcntl.LOCK_NB)
    except OSError:
        _os.close(fd)
        return None
    return fd


def release_refresh_lock(fd: int) -> None:
    """Release the ``flock`` held by *fd* (see [`acquire_refresh_lock`][terok_sandbox.vault.daemon.token_broker.acquire_refresh_lock])."""
    import os as _os

    try:
        _os.close(fd)
    except OSError as exc:
        _logger.debug("refresh lock close failed: %s", exc)
