# SPDX-FileCopyrightText: 2026 Jiri Vyskocil
# SPDX-License-Identifier: Apache-2.0

"""Credential proxy lifecycle management.

Manages the ``terok-credential-proxy`` daemon: start, stop, status, and
pre-task health checks.  Mirrors the gate server pattern from
:mod:`gate_server` but simpler (daemon-only for now; systemd socket
activation can be added later).

**No auto-start.**  Task creation checks reachability via
:func:`ensure_proxy_reachable` and fails with an actionable error
rather than silently starting a daemon.
"""

from __future__ import annotations

import os
import signal
import subprocess
from dataclasses import dataclass
from pathlib import Path

from .config import SandboxConfig


def _cfg(cfg: SandboxConfig | None = None) -> SandboxConfig:
    """Return *cfg* or a default :class:`SandboxConfig`."""
    return cfg or SandboxConfig()


# ---------- Data classes ----------


@dataclass(frozen=True)
class CredentialProxyStatus:
    """Current state of the credential proxy."""

    running: bool
    """Whether the proxy daemon is currently alive."""

    socket_path: Path
    """Configured Unix socket path."""

    db_path: Path
    """Configured credential database path."""


# ---------- PID file helpers ----------


def _pid_file(cfg: SandboxConfig | None = None) -> Path:
    """Return the PID file path for the managed proxy daemon."""
    return _cfg(cfg).proxy_pid_file_path


def _is_managed_proxy(pid: int, cfg: SandboxConfig | None = None) -> bool:
    """Return whether *pid* was started with the expected PID file argument."""
    cmdline_path = Path(f"/proc/{pid}/cmdline")
    if not cmdline_path.is_file():
        return False
    try:
        raw = cmdline_path.read_bytes()
    except OSError:
        return False
    args = raw.rstrip(b"\x00").split(b"\x00")
    args_str = [a.decode("utf-8", errors="ignore") for a in args]
    expected = f"--pid-file={_pid_file(cfg)}"
    return expected in args_str


# ---------- Public API ----------


def start_daemon(cfg: SandboxConfig | None = None) -> None:
    """Start a ``terok-credential-proxy`` daemon process.

    The proxy listens on a Unix socket and reads credentials from a
    sqlite3 database.  A routes JSON file must exist at the configured
    path (generated by terok-agent from the YAML registry).

    Writes a PID file to ``runtime_root() / "credential-proxy.pid"``.
    """
    c = _cfg(cfg)
    sock_path = c.proxy_socket_path
    db_path = c.proxy_db_path
    routes_path = c.proxy_routes_path
    pidfile = _pid_file(cfg)

    sock_path.parent.mkdir(parents=True, exist_ok=True)
    pidfile.parent.mkdir(parents=True, exist_ok=True)

    if not routes_path.is_file():
        raise SystemExit(
            f"Proxy routes file not found: {routes_path}\n"
            "Run 'terokctl auth <provider>' first to configure credentials,\n"
            "or create a routes.json manually."
        )

    cmd = [
        "terok-credential-proxy",
        f"--socket-path={sock_path}",
        f"--db-path={db_path}",
        f"--routes-file={routes_path}",
        f"--pid-file={pidfile}",
    ]

    # Fork into background so the proxy survives shell exit.
    # The server writes its own PID file via --pid-file.
    import time

    proc = subprocess.Popen(
        cmd,
        stdout=subprocess.DEVNULL,
        stderr=subprocess.PIPE,
        start_new_session=True,
    )

    # Brief wait to catch immediate startup failures (bad args, missing deps)
    time.sleep(0.3)
    ret = proc.poll()
    if ret is not None:
        stderr = (proc.stderr.read() or b"").decode(errors="replace").strip()
        msg = f"Credential proxy failed to start (exit {ret})"
        if stderr:
            msg += f":\n{stderr}"
        raise SystemExit(msg)


def stop_daemon(cfg: SandboxConfig | None = None) -> None:
    """Stop the managed proxy daemon by sending SIGTERM."""
    pidfile = _pid_file(cfg)
    if not pidfile.is_file():
        return
    try:
        pid = int(pidfile.read_text().strip())
        if _is_managed_proxy(pid, cfg):
            os.kill(pid, signal.SIGTERM)
    except (ValueError, ProcessLookupError, PermissionError):
        pass
    finally:
        if pidfile.is_file():
            pidfile.unlink()


def is_daemon_running(cfg: SandboxConfig | None = None) -> bool:
    """Check whether the managed proxy daemon is alive via its PID file."""
    pidfile = _pid_file(cfg)
    if not pidfile.is_file():
        return False
    try:
        pid = int(pidfile.read_text().strip())
        if not _is_managed_proxy(pid, cfg):
            return False
        os.kill(pid, 0)  # signal 0 = existence check
        return True
    except (ValueError, ProcessLookupError, PermissionError):
        return False


def get_proxy_status(cfg: SandboxConfig | None = None) -> CredentialProxyStatus:
    """Return the current credential proxy status."""
    c = _cfg(cfg)
    return CredentialProxyStatus(
        running=is_daemon_running(cfg),
        socket_path=c.proxy_socket_path,
        db_path=c.proxy_db_path,
    )


def ensure_proxy_reachable(cfg: SandboxConfig | None = None) -> None:
    """Verify the credential proxy is running.

    Raises ``SystemExit`` with an actionable message if the proxy is down.
    Called before task creation when credential proxy is enabled.
    """
    if is_daemon_running(cfg):
        return

    c = _cfg(cfg)
    msg = (
        "Credential proxy is not running.\n"
        "\n"
        "The credential proxy injects real API credentials into container\n"
        "requests without exposing secrets to the container filesystem.\n"
        "\n"
        f"Start it with:\n  terok-sandbox proxy start\n"
        f"\n"
        f"Socket: {c.proxy_socket_path}\n"
        f"DB:     {c.proxy_db_path}\n"
    )
    raise SystemExit(msg)
